name: "finaletoolkit_mds"
description: |
  Comnpute the Motif Diversity Score using normalized Shannon entropy
  (Jiang et al., 2020).
keywords:
  - end-motifs
  - genomics
  - fragmentomics
tools:
  - "finaletoolkit":
      description: "Extract cfDNA fragmentation features from sequencing data."
      homepage: "https://epifluidlab.github.io/FinaleToolkit/"
      documentation: "https://epifluidlab.github.io/FinaleToolkit/documentation/index.html"
      tool_dev_url: "https://github.com/epifluidlab/FinaleToolkit"
      doi: "10.1093/bioadv/vbaf236"
      licence:
        - "MIT"
      identifier: biotools:finaletoolkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - motifs:
        type: file
        description: TSV file containing k-mer frequencies for end motifs
        pattern: "*.tsv"
        ontologies:
          - edam: "http://edamontology.org/format_3475"
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}.tsv":
          type: file
          pattern: "*.tsv"
          description: |
            Two-column TSV file containing the MDS for the sample.
          ontologies:
            - edam: "http://edamontology.org/format_3475"
  versions_finaletoolkit:
    - - ${task.process}:
          type: string
          description: The name of the process
      - finaletoolkit:
          type: string
          description: The name of the tool
      - finaletoolkit --version | sed 's/FinaleToolkit //g':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - finaletoolkit:
          type: string
          description: The name of the tool
      - finaletoolkit --version | sed 's/FinaleToolkit //g':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@lbeltrame"
maintainers:
  - "@lbeltrame"
