name: gapseq_medium
description: Predict growth medium from a draft model and pathway predictions
keywords:
  - metabolic model
  - growth medium
  - gap filling
  - gapseq
  - bacteria
  - genome-scale model
tools:
  - gapseq:
      description: |
        gapseq predicts a growth medium from a draft model and pathway predictions.
      homepage: https://github.com/jotech/gapseq
      documentation: https://gapseq.readthedocs.io/
      tool_dev_url: https://github.com/jotech/gapseq
      doi: "10.1186/s13059-021-02295-1"
      licence:
        - "AGPL-3.0-only"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - draft:
        type: file
        description: Draft model from gapseq draft
        pattern: "*.RDS"
        ontologies: []
    - pathways:
        type: file
        description: Pathway prediction table from gapseq find
        pattern: "*-all-Pathways.tbl"
        ontologies: []
output:
  medium:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csv":
          type: file
          description: Predicted growth medium CSV file
          pattern: "*.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: Log files from gapseq medium prediction
          pattern: "*.log"
          ontologies: []
  versions_gapseq:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gapseq:
          type: string
          description: The name of the tool
      - gapseq -v 2>&1 | grep -oP "\d+\.\d+\.\d+":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gapseq:
          type: string
          description: The name of the tool
      - gapseq -v 2>&1 | grep -oP "\d+\.\d+\.\d+":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@brovolia"
maintainers:
  - "@brovolia"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/gapseq:2.1.0--4c3c0957c0119f60
      build_id: bd-4c3c0957c0119f60_1
      scan_id: sc-c00b3946e67c8a79_1
    linux/amd64:
      name: community.wave.seqera.io/library/gapseq:2.1.0--c32b876ebb5e5f5b
      build_id: bd-c32b876ebb5e5f5b_1
      scan_id: sc-4e37209a42665a56_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/gapseq:2.1.0--2d31362fa54fb0b1
      build_id: bd-2d31362fa54fb0b1_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/87/8765d29d9128a4e47bcff3f2182362aacb6b4a1499ab774713fe34ce9e821e0b/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/gapseq:2.1.0--860639694c942c89
      build_id: bd-860639694c942c89_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/93/933e301b11c1ec1699da6382e9e35b0e4e31edb80763eb2fa1b69ad7d6d1e5c7/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/gapseq/medium/.conda-lock/linux_amd64-bd-c32b876ebb5e5f5b_1.txt
    linux/arm64:
      lock_file: modules/nf-core/gapseq/medium/.conda-lock/linux_arm64-bd-4c3c0957c0119f60_1.txt
