---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::nimfa=1.4.0
  - conda-forge::numpy=2.3.3
  - conda-forge::pip=25.2
  - conda-forge::python=3.13.7
  - conda-forge::scikit-learn=1.7.2
  - conda-forge::scipy=1.16.2
  - pip:
      - SigProfilerAssignment==0.2.6
      - SigProfilerExtractor==1.2.2
      - SigProfilerMatrixGenerator==1.3.5
      - pandas==2.3.2
      - sigProfilerPlotting==1.4.1

