name: deeparg_downloaddata
description: A deep learning based approach to predict Antibiotic Resistance
  Genes (ARGs) from metagenomes
keywords:
  - download
  - database
  - deeparg
  - antimicrobial resistance genes
  - deep learning
  - prediction
tools:
  - deeparg:
      description: A deep learning based approach to predict Antibiotic Resistance
        Genes (ARGs) from metagenomes
      homepage: https://github.com/gaarangoa/deeparg
      documentation: https://github.com/gaarangoa/deeparg
      tool_dev_url: https://github.com/gaarangoa/deeparg
      doi: "10.1186/s40168-018-0401-z"
      licence:
        - "MIT"
      identifier: ""
input: []
output:
  db:
    - db/:
        type: directory
        description: Directory containing database required for deepARG.
        pattern: "db/"
  versions_deeparg:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeparg:
          type: string
          description: The name of the tool
      - 1.0.4:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeparg:
          type: string
          description: The name of the tool
      - 1.0.4:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
