# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "aardvark_merge"
description: A tool to evaluate and merge multiple variant calls into a consensus VCF.
keywords:
  - variant calling
  - vcf
  - comparison
  - consensus
  - merging
tools:
  - aardvark:
      description: |
        The aardvark merge command provides a method to merge variant calls. This functionality is helpful when multiple 
        variant callers or technologies are used for the same sample. Merging variant sets can be complex and Aardvark 
        simplifies this process by modeling the variants as haplotypes. This allows for different merge strategies for 
        resolving conflicting variant sets.
      homepage: "https://github.com/PacificBiosciences/aardvark"
      documentation: "https://github.com/PacificBiosciences/aardvark/blob/main/docs/methods.md#merge-strategies"
      tool_dev_url: "https://github.com/PacificBiosciences/aardvark"
      doi: "10.1101/2025.10.03.680257"
      licence: ["MIT"]
      identifier: biotools:aardvark

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - vcfs:
        type: file
        description: List of VCF files to be merged
        pattern: "*.{vcf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016"
    - indexes:
        type: file
        description: List of index files for the input VCF files
        pattern: "*.{vcf.gz.tbi,vcf.gz.csi,tbi,csi}"
  - - meta2:
        type: map
        description: Groovy Map containing reference fasta information
    - fasta:
        type: file
        description: Reference genome fasta file
        pattern: "*.{fasta,fa,fasta.gz,fa.gz}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - - meta3:
        type: map
        description: Groovy Map containing bed information
    - bed:
        type: file
        description: Optional BED file containing genomic regions to restrict the merge operation
        pattern: "*.{bed}"
        ontologies:
          - edam: "http://edamontology.org/format_3586"

output:
  summary:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.summary.tsv":
          type: file
          description: Global summary statistics of the variant merge
          pattern: "*.summary.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3475" # TSV
  passing_vcf:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.passing.vcf.gz":
          type: file
          description: Merged VCF file containing passing variants
          pattern: "*.passing.vcf.gz"
          ontologies:
          - edam: "http://edamontology.org/format_3016"
  passing_vcf_index:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.passing.vcf.gz.tbi":
          type: file
          description: Index file for the merged passing VCF
          pattern: "*.passing.vcf.gz.tbi"
  passing_regions:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.regions.bed.gz":
          type: file
          description: BED file of regions containing passing variants
          pattern: "*.regions.bed.gz"
          ontologies:
          - edam: "http://edamontology.org/format_3586"
  passing_regions_index:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.regions.bed.gz.tbi":
          type: file
          description: Index file for the passing regions BED
          pattern: "*.regions.bed.gz.tbi"
  failed_regions:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.failed_regions.bed.gz":
          type: file
          description: BED file of regions that failed merging criteria
          pattern: "*.failed_regions.bed.gz"
          ontologies:
          - edam: "http://edamontology.org/format_3586"
  failed_regions_index:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.failed_regions.bed.gz.tbi":
          type: file
          description: Index file for the failed regions BED
          pattern: "*.failed_regions.bed.gz.tbi"
  runinfo:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.json":
          type: file
          description: JSON file containing parameter settings used during the run
          pattern: "*.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  versions_aardvark:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "aardvark":
          type: string
          description: The name of the tool
      - "aardvark merge --version 2>&1 | sed 's/aardvark-bio-merge //; s/-conda//'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "aardvark":
          type: string
          description: The name of the tool
      - "aardvark merge --version 2>&1 | sed 's/aardvark-bio-merge //; s/-conda//'":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"