---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.10.19
  - conda-forge::pip=25.2
  - pip:
      - refineGEMs==0.1.23
