name: paftools_sam2paf
description: A program to convert bam into paf.
keywords:
  - paf
  - bam
  - conversion
tools:
  - paftools:
      description: |
        A program to manipulate paf files / convert to and from paf.
      homepage: https://github.com/lh3/minimap2
      documentation: https://github.com/lh3/minimap2/blob/master/README.md
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: An input bam file to be converted into paf.
        ontologies: []
output:
  paf:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  versions_samtools:
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_paftools:
    - - ${task.process}:
          type: string
          description: Name of the process
      - paftools:
          type: string
          description: Name of the tool
      - paftools.js version:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: Name of the process
      - paftools:
          type: string
          description: Name of the tool
      - paftools.js version:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
