name: "bbmap_repair"
description: Re-pairs reads that became disordered or had some mates eliminated.
keywords:
  - paired reads re-pairing
  - fastq
  - preprocessing
tools:
  - repair:
      description: Repair.sh is a tool that re-pairs reads that became disordered
        or had some mates eliminated tools.
      homepage: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/
      documentation: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      licence:
        - "UC-LBL license (see package)"
      identifier: biotools:bbmap
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - reads:
        type: file
        description: |
          List of input paired end fastq files
        pattern: "*.{fastq,fq}.gz"
        ontologies:
          - edam: http://edamontology.org/format_1930 # FASTQ
  - interleave:
      type: boolean
      description: |
        Indicates whether the input paired reads are interleaved or not
output:
  repaired:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_repaired.fastq.gz":
          type: file
          description: re-paired reads
          pattern: "*_repaired.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  singleton:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}_singleton.fastq.gz:
          type: file
          description: singleton reads
          pattern: "*singleton.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  log:
    - "*.log":
        type: file
        description: log file containing stdout and stderr from repair.sh
        pattern: "*.log"
        ontologies: []
  versions_bbmap:
    - - "${task.process}":
          type: string
          description: The name of the process
      - bbmap:
          type: string
          description: The name of the tool
      - bbversion.sh | grep -v "Duplicate cpuset":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - bbmap:
          type: string
          description: The name of the tool
      - bbversion.sh | grep -v "Duplicate cpuset":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@mazzalab"
maintainers:
  - "@mazzalab"
  - "@tm4zza"
