name: "mudskipper_index"
description: Build and store a gtf index, which is useful for converting genomic BAM/SAM files to transcriptomic BAM/SAM files.
keywords:
  - bam
  - transcriptome
  - transcriptomic
  - index
  - mudskipper
  - sam
tools:
  - "mudskipper":
      description: "mudskipper is a tool for converting genomic BAM/SAM files to transcriptomic BAM/RAD files."
      homepage: "https://github.com/OceanGenomics/mudskipper"
      documentation: "https://github.com/OceanGenomics/mudskipper"
      tool_dev_url: "https://github.com/OceanGenomics/mudskipper"
      licence:
        - "BSD 3-clause"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing annotation information
          e.g. `[ id:'genome' ]`
    - gtf:
        type: file
        description: Transcript annotation file.
        pattern: "*.{gtf,gff,gff3}"
        ontologies: []
output:
  index:
    - - meta:
          type: map
          description: |
            Groovy Map containing annotation information
            e.g. `[ id:'genome' ]`
      - ${prefix}/:
          type: directory
          description: Mudskipper index for running mudskipper conversion tools
          pattern: "${prefix}/"
  versions_mudskipper:
    - - ${task.process}:
          type: string
          description: The name of the process
      - mudskipper:
          type: string
          description: The name of the tool
      - mudskipper -V 2>&1 | sed 's/.*mudskipper //':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - mudskipper:
          type: string
          description: The name of the tool
      - mudskipper -V 2>&1 | sed 's/.*mudskipper //':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@anoronh4"
