name: pairtools_merge
description: Merge multiple pairs/pairsam files
keywords:
  - merge
  - pairs
  - pairsam
tools:
  - pairtools:
      description: CLI tools to process mapped Hi-C data
      homepage: http://pairtools.readthedocs.io/
      documentation: http://pairtools.readthedocs.io/
      tool_dev_url: https://github.com/mirnylab/pairtools
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - allpairs:
        type: file
        description: All pair files to merge
        ontologies: []
output:
  pairs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*pairs.gz":
          type: file
          description: Merged pairs file
          pattern: "*.{pairs.gz}"
          ontologies: []
  versions_pairtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pairtools:
          type: string
          description: The name of the tool
      - pairtools --version | sed 's/.*pairtools.*version //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pairtools:
          type: string
          description: The name of the tool
      - pairtools --version | sed 's/.*pairtools.*version //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nservant"
maintainers:
  - "@nservant"
