build:
	echo "INTERPROSCAN_VER:" ${INTERPROSCAN_VER}
	DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build . -t quay.io/nf-core/interproscan:${INTERPROSCAN_VER}

push:
	echo "INTERPROSCAN_VER:" ${INTERPROSCAN_VER}
	DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build . -t quay.io/nf-core/interproscan:${INTERPROSCAN_VER}