# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_qc_picard
description: Produces comprehensive statistics from BAM file
keywords:
  - statistics
  - counts
  - hs_metrics
  - wgs_metrics
  - bam
  - sam
  - cram
components:
  - picard/collectmultiplemetrics
  - picard/collectwgsmetrics
  - picard/collecthsmetrics
input:
  - ch_bam_bai_bait_target:
      type: file
      description: |
        BAM/CRAM/SAM file, its index, and optionally an interval list or bed file
        with the locations of the baits used and one with the locations of the targets.
        The bait and target intervals may be empty lists, in which case WGS metrics
        are collected instead of hybrid-selection metrics.

        Structure: [ val(meta), path(bam), path(bai), path(bait_intervals), path(target_intervals) ]
  - ch_fasta:
      type: file
      description: |
        Reference fasta file.

        Structure: [ val(meta2), path(fasta) ]
      pattern: "*.{fasta,fa,fna}"
  - ch_fasta_fai:
      type: file
      description: |
        Reference fasta file index.

        Structure: [ val(meta2), path(fai) ]
      pattern: "*.{fasta,fa,fna}.fai"
  - ch_fasta_dict:
      type: file
      description: |
        Reference fasta sequence dictionary.

        Structure: [ val(meta2), path(dict) ]
      pattern: "*.dict"
  - ch_fasta_gzi:
      type: file
      description: |
        Index of a bgzipped reference fasta file.

        Structure: [ val(meta2), path(gzi) ]
      pattern: "*.gzi"
output:
  - coverage_metrics:
      type: file
      description: |
        Alignment metrics files generated by picard CollectHsMetrics or CollectWgsMetrics.

        Structure: [ val(meta), path(coverage_metrics) ]
      pattern: "*_metrics.txt"
  - multiple_metrics:
      type: file
      description: |
        Alignment metrics files generated by picard CollectMultipleMetrics.

        Structure: [ val(meta), [ path(multiple_metrics) ] ]
      pattern: "*_{metrics}"
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
