name: bwameth_index
description: Performs indexing of c2t converted reference genome
keywords:
  - bwameth
  - 3-letter genome
  - index
  - methylseq
  - bisulphite
  - bisulfite
  - fasta
tools:
  - bwameth:
      description: |
        Fast and accurate alignment of BS-Seq reads
        using bwa-mem and a 3-letter genome.
      homepage: https://github.com/brentp/bwa-meth
      documentation: https://github.com/brentp/bwa-meth
      arxiv: arXiv:1401.1129
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies: []
  - use_mem2:
      type: boolean
      description: |
        If true, use bwameth index-mem2 for indexing. If false, use bwameth index (default: false)
output:
  index:
    - - meta:
          type: directory
          description: Directory containing bwameth genome index
          pattern: "index"
      - BwamethIndex:
          type: directory
          description: Directory containing bwameth genome index
          pattern: "index"
  versions_bwameth_index:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwameth:
          type: string
          description: The name of the tool
      - bwameth.py --version | cut -f2 -d' ':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwameth:
          type: string
          description: The name of the tool
      - bwameth.py --version | cut -f2 -d' ':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@phue"
maintainers:
  - "@phue"
  - "@sateeshperi"
