channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::pip=25.0.1
  - conda-forge::python=3.11.11
  - conda-forge::setuptools=75.8
  - pip:
      - metaspace-converter==1.1.1
      - spatialdata==0.3.0
      - spatial_image==1.2.1
