---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::hifi_trimmer=4.0.0
  - bioconda::htslib=1.24
  - bioconda::samtools=1.24
