name: "orthofinder3"
description: OrthoFinder is a fast, accurate and comprehensive platform for
  comparative genomics.
keywords:
  - genomics
  - orthogroup
  - orthologs
  - gene
  - duplication
  - tree
  - phylogeny
tools:
  - "orthofinder":
      description: "Accurate inference of orthogroups, orthologues, gene trees and rooted
        species tree made easy!"
      homepage: "https://github.com/davidemms/OrthoFinder"
      documentation: "https://github.com/davidemms/OrthoFinder"
      tool_dev_url: "https://github.com/davidemms/OrthoFinder"
      doi: "10.1186/s13059-019-1832-y"
      licence: ["GPL v3"]
      identifier: biotools:OrthoFinder
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fastas:
        type: list
        description: Input fasta files
        pattern: "*.{fa,faa,fasta,fas,pep}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing a name
          e.g. `[ id:'folder1' ]`
    - prior_run:
        type: directory
        description: |
          A folder containing a previous WorkingDirectory from OrthoFinder.
output:
  orthofinder:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "$prefix":
          type: directory
          description: OrthoFinder output directory
  working:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "$prefix/WorkingDirectory":
          type: directory
          description: OrthoFinder WorkingDirectory (used for the resume function)
  versions_orthofinder:
    - - "${task.process}":
          type: string
          description: The name of the process
      - orthofinder:
          type: string
          description: The name of the tool
      - "orthofinder --version 2>&1 | tail -1 | sed 's/\\x1b\\[[0-9;]*m//g; s/OrthoFinder:v//'":
          type: eval
          description: The version of OrthoFinder
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from
      - orthofinder:
          type: string
          description: The tool name
      - "orthofinder --version 2>&1 | tail -1 | sed 's/\\x1b\\[[0-9;]*m//g; s/OrthoFinder:v//'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@GallVp"
  - "@chriswyatt1"
maintainers:
  - "@GallVp"
  - "@chriswyatt1"
