name: "fcs_fcsgx"
description: Run FCS-GX on assembled genomes. The contigs of the assembly are
  searched against a reference database excluding the given taxid.
keywords:
  - assembly
  - genomics
  - quality control
  - contamination
  - NCBI
tools:
  - "fcs":
      description: |
        "The Foreign Contamination Screening (FCS) tool rapidly detects contaminants from foreign
        organisms in genome assemblies to prepare your data for submission. Therefore, the
        submission process to NCBI is faster and fewer contaminated genomes are submitted.
        This reduces errors in analyses and conclusions, not just for the original data submitter
        but for all subsequent users of the assembly."
      homepage: "https://www.ncbi.nlm.nih.gov/data-hub/cgr/data-quality-tools/"
      documentation: "https://github.com/ncbi/fcs/wiki/FCS-GX"
      tool_dev_url: "https://github.com/ncbi/fcs"
      license:
        - "United States Government Work"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - assembly:
        type: file
        description: assembly fasta file
        ontologies: []
    - taxid:
        type: string
        description: Taxonomic id (e.g. "6973")
  - gxdb:
      type: file
      description: The NCBI GenBank database to search against.
      ontologies: []
output:
  fcs_gx_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - out/*.fcs_gx_report.txt:
          type: file
          description: Report containing the contig identifier and recommended
            action (EXCLUDE, TRIM, FIX, REVIEW)
          pattern: "*.fcs_gx_report.txt"
          ontologies: []
  taxonomy_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - out/*.taxonomy.rpt:
          type: file
          description: Report containing the contig identifier and mapped
            contaminant species
          pattern: "*.taxonomy.rpt"
          ontologies: []
  versions_fcsadaptor:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fcsadaptor:
          type: string
          description: The name of the tool
      - 0.4.0:
          type: string
          description: The expression to obtain the version of the tool
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python3 --version |& sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fcsadaptor:
          type: string
          description: The name of the tool
      - 0.4.0:
          type: string
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python3 --version |& sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@tillenglert"
maintainers:
  - "@tillenglert"
