name: kraken2_kraken2
description: Classifies metagenomic sequence data
keywords:
  - classify
  - metagenomics
  - fastq
  - db
tools:
  - kraken2:
      description: |
        Kraken2 is a taxonomic sequence classifier that assigns taxonomic labels to sequence reads
      homepage: https://ccb.jhu.edu/software/kraken2/
      documentation: https://github.com/DerrickWood/kraken2/wiki/Manual
      doi: 10.1186/s13059-019-1891-0
      publication:
        author: "Wood D.E., Lu J. & Langmead B."
        year: 2019
        title: "Improved metagenomic analysis with Kraken 2"
        source: "Genome Biology"
      licence: ["MIT"]
      identifier: biotools:kraken2
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []
  - db:
      type: directory
      description: Kraken2 database
  - save_output_fastqs:
      type: string
      description: |
        If true, optional commands are added to save classified and unclassified reads
        as fastq files
  - save_reads_assignment:
      type: string
      description: |
        If true, an optional command is added to save a file reporting the taxonomic
        classification of each input read
output:
  classified_reads_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.classified{.,_}*":
          type: file
          description: |
            Reads classified as belonging to any of the taxa
            on the Kraken2 database.
          pattern: "*{fastq.gz}"
          ontologies: []
  unclassified_reads_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.unclassified{.,_}*":
          type: file
          description: |
            Reads not classified to any of the taxa
            on the Kraken2 database.
          pattern: "*{fastq.gz}"
          ontologies: []
  classified_reads_assignment:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*classifiedreads.txt":
          type: file
          description: |
            Kraken2 output file indicating the taxonomic assignment of
            each input read
          ontologies: []
  report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*report.txt":
          type: file
          description: |
            Kraken2 report containing stats about classified
            and not classified reads.
          pattern: "*.{report.txt}"
          ontologies: []
  versions_kraken2:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - kraken2:
          type: string
          description: The tool name
      - kraken2 --version 2>&1 | head -1 | sed "s/^.*Kraken version //; s/ .*//":
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - pigz:
          type: string
          description: The tool name
      - pigz --version 2>&1 | sed "s/pigz //g":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - kraken2:
          type: string
          description: The tool name
      - kraken2 --version 2>&1 | head -1 | sed "s/^.*Kraken version //; s/ .*//":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - pigz:
          type: string
          description: The tool name
      - pigz --version 2>&1 | sed "s/pigz //g":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@joseespinosa"
  - "@drpatelh"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/kraken2_coreutils_pigz:b111fc3860b64b23
      build_id: bd-b111fc3860b64b23_1
      scan_id: sc-6976dfb99f2bfdc4_1
    linux/arm64:
      name: community.wave.seqera.io/library/kraken2_coreutils_pigz:7d7b46e5b5cc0202
      build_id: bd-7d7b46e5b5cc0202_1
      scan_id: sc-d9823d3c8ed09ebf_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/kraken2_coreutils_pigz:2e813a040b8167c6
      build_id: bd-2e813a040b8167c6_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/7c/7c9e4afffe492bf3766631f44c6e04530859d124fb1bc7962ca734abbf63d0b4/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/kraken2_coreutils_pigz:6647bf0cf5a34e5b
      build_id: bd-6647bf0cf5a34e5b_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/ec/ec5af88da27c32c52b667af2af67ce76ffc96715c1a40e0f4ab72dd87623adfa/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/kraken2/kraken2/.conda-lock/linux_amd64-bd-b111fc3860b64b23_1.txt
    linux/arm64:
      lock_file: modules/nf-core/kraken2/kraken2/.conda-lock/linux_arm64-bd-7d7b46e5b5cc0202_1.txt
