name: "ctatsplicing_prepgenomelib"
description: Reference preparation for CTAT-splicing
keywords:
  - splicing
  - cancer
  - rna
  - rnaseq
tools:
  - "ctatsplicing":
      description: "Detection and annotation of cancer splicing aberrations"
      homepage: "https://github.com/TrinityCTAT/CTAT-SPLICING"
      documentation: "https://github.com/TrinityCTAT/CTAT-SPLICING"
      tool_dev_url: "https://github.com/TrinityCTAT/CTAT-SPLICING"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - genome_lib:
        type: file
        description: CTAT genome library reference
        pattern: "*"
        ontologies: []
  - cancer_intron_tsv:
      type: file
      description: CTAT-splicing data resource supplement
      ontologies: []
output:
  reference:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - genome_lib:
          type: file
          description: Modified CTAT genome library reference
          pattern: "*"
          ontologies: []
  versions_ctatsplicing:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ctatsplicing:
          type: string
          description: The name of the tool
      - 0.0.3:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ctatsplicing:
          type: string
          description: The name of the tool
      - 0.0.3:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@anoronh4"
  - "@nvnieuwk"
maintainers:
  - "@anoronh4"
long_description: |
  This module prepares the CTAT genome library reference for splicing analysis by integrating cancer intron annotations.
  It takes a CTAT genome library and a cancer intron TSV file as input, and outputs a modified genome library reference.
  The output can be used in subsequent CTAT-splicing analyses to detect and annotate cancer splicing aberrations.
  Make sure to provide the correct genome library and cancer intron data resource.
