name: "finaletoolkit_delfi"
description: Generate a binned fragment profile and a fragment distribution histogram
keywords:
  - sort
  - genomics
  - fragmentomics
tools:
  - "finaletoolkit":
      description: "Extract cfDNA fragmentation features from sequencing data."
      homepage: "https://epifluidlab.github.io/FinaleToolkit/"
      documentation: "https://epifluidlab.github.io/FinaleToolkit/documentation/index.html"
      tool_dev_url: "https://github.com/epifluidlab/FinaleToolkit"
      doi: "10.1093/bioadv/vbaf236"
      licence:
        - "MIT"
      identifier: biotools:finaletoolkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Sorted BAM file
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
    - bai:
        type: file
        description: BAM file index
        pattern: "*.bai"
        ontologies:
          - edam: "http://edamontology.org/format_3327" # BAI
  - bins:
      type: file
      description: |
        BED containing binned genomic coordinates
      pattern: "*.bed"
      ontologies:
        - edam: "http://edamontology.org/format_3003" # BED
  - chromosome_sizes:
      type: file
      pattern: "*.sizes"
      description: |
        Two-column file containing the size for each chromosome
      ontologies:
        - edam: "http://edamontology.org/format_3475" # TSV
  - genome_2bit:
      type: file
      description: |
        2bit compressed genome file (must be the same as the one used for the
        BAM file)
      pattern: "*.2bit"
      ontologies:
        - edam: "http://edamontology.org/format_3009" # 2bit
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed":
          type: file
          pattern: "*.bed"
          description: |
            BED file containing DELFI scores
          ontologies:
            - edam: "http://edamontology.org/format_3003" # BED
  versions_finaletoolkit:
    - - ${task.process}:
          type: string
          description: The name of the process
      - finaletoolkit:
          type: string
          description: The name of the tool
      - "finaletoolkit --version | sed 's/FinaleToolkit //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - finaletoolkit:
          type: string
          description: The name of the tool
      - "finaletoolkit --version | sed 's/FinaleToolkit //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@lbeltrame"
maintainers:
  - "@lbeltrame"
