name: bbmap_index
description: Creates an index from a fasta file, ready to be used by bbmap.sh in
  mapping mode.
keywords:
  - map
  - index
  - fasta
tools:
  - bbmap:
      description: BBMap is a short read aligner, as well as various other
        bioinformatic tools.
      homepage: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      documentation: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
      licence:
        - "UC-LBL license (see package)"
      identifier: biotools:bbmap
input:
  - fasta:
      type: file
      description: fasta formatted file with nucleotide sequences
      pattern: "*.{fna,fa,fasta}"
      ontologies: []
output:
  index:
    - ref:
        type: directory
        description: Directory containing the index files
  versions_bbmap:
    - - "${task.process}":
          type: string
          description: The name of the process
      - bbmap:
          type: string
          description: The name of the tool
      - bbversion.sh | grep -v "Duplicate cpuset":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - bbmap:
          type: string
          description: The name of the tool
      - bbversion.sh | grep -v "Duplicate cpuset":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@erikrikarddaniel"
maintainers:
  - "@erikrikarddaniel"
