name: "pbtk_pbmerge"
description: Simple tool which merges several PacBio BAM files together
keywords:
  - pbtk
  - pbmerge
  - genomics
  - pacbio
  - bam
tools:
  - "pbtk":
      description: "pbtk - PacBio BAM toolkit"
      homepage: "https://github.com/PacificBiosciences/pbtk"
      documentation: "https://github.com/PacificBiosciences/pbtk#usage"
      tool_dev_url: "https://github.com/PacificBiosciences/pbtk"
      doi: "no DOI available"
      licence:
        - "BSD-3-clause-Clear"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bams:
        type: file
        description: PacBio BAM files
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM

output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bam":
          type: file
          description: The merged PacBio BAM file
          pattern: "*.bam"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
  pbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.pbi":
          type: file
          description: BAM Pacbio index file
          pattern: "*.bam.pbi"
          ontologies: []
  versions_pbmerge:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pbtk:
          type: string
          description: The name of the tool
      - pbmerge --version | head -n1 | sed 's/pbmerge //' | sed -E 's/ .+//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pbtk:
          type: string
          description: The name of the tool
      - pbmerge --version | head -n1 | sed 's/pbmerge //' | sed -E 's/ .+//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@haidyi"
maintainers:
  - "@haidyi"
