name: "foldseek_createdb"
description: Create a database from protein structures
keywords:
  - protein
  - structure
  - comparisons
tools:
  - "foldseek":
      description: "Foldseek: fast and accurate protein structure search"
      homepage: "https://search.foldseek.com/search"
      documentation: "https://github.com/steineggerlab/foldseek"
      tool_dev_url: "https://github.com/steineggerlab/foldseek"
      doi: "10.1038/s41587-023-01773-0"
      licence:
        - "GPL v3"
      identifier: biotools:foldseek
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - pdb:
        type: file
        description: Protein structure(s) in PDB, mmCIF or mmJSON format (also
          works with folder input)
        pattern: "*.{pdb,mmcif,mmjson}"
        ontologies:
          - edam: "http://edamontology.org/format_1476" # PDB
          - edam: "http://edamontology.org/format_1477" # mmCIF
output:
  db:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - ${prefix}:
          type: directory
          description: Directory containing pdb database files
          pattern: "*"
  versions_foldseek:
    - - ${task.process}:
          type: string
          description: The name of the process
      - foldseek:
          type: string
          description: The name of the tool
      - "foldseek --help |& sed -n 's/.*Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - foldseek:
          type: string
          description: The name of the tool
      - "foldseek --help |& sed -n 's/.*Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@vagkaratzas"
