name: wisecondorx_convert
description: Converts a BAM file to a WisecondorX-compatible .npz file for downstream copy number variation analysis of cell-free DNA.
keywords:
  - wisecondorx
  - cfDNA
  - copy number
  - liquid biopsy
  - cancer
tools:
  - wisecondorx:
      description: WIthin-SamplE COpy Number aberration DetectOR for cell-free DNA.
      homepage: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX
      documentation: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX
      tool_dev_url: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: Groovy Map containing sample information e.g. [ id:'sample1' ]
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.bam"
  - bai:
      type: file
      description: BAM index file
      pattern: "*.bai"

output:
  - meta:
      type: map
      description: Groovy Map containing sample information e.g. [ id:'sample1' ]
  - npz:
      type: file
      description: Compressed numpy file for use with WisecondorX newref and predict
      pattern: "*.npz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@JP-Bro"
maintainers:
  - "@JP-Bro"