# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "macse_refinealignment"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "macse":
      description: "MACSE: Multiple Alignment of Coding SEquences Accounting for Frameshifts
        and Stop Codons."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ["CeCILL 2.1"]
      identifier: biotools:macse

input:
  ### TODO nf-core: Add a description of all of the variables used as input
  fas:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fas{.gz,}":
          type: file
          description: Aligned sequences in FASTA format. May be gzipped or uncompressed.
          pattern: "*.fas{.gz,}"
          ontologies:
            - edam: http://edamontology.org/format_2554 # ALIGNMENT FORMAT TXT
            - edam: http://edamontology.org/format_1921 # ALIGNMENT FORMAT
            - edam: http://edamontology.org/format_1984 # FASTA-ALN
output:
  ### TODO nf-core: Add a description of all of the variables used as output
  result_fas_NT:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fas{.gz,}":
          type: file
          description: Aligned sequences in FASTA format. May be gzipped or uncompressed.
          pattern: "*_NT"
          ontologies:
            - edam: http://edamontology.org/format_2554 # ALIGNMENT FORMAT TXT
            - edam: http://edamontology.org/format_1921 # ALIGNMENT FORMAT
            - edam: http://edamontology.org/format_1984 # FASTA-ALN
  result_fas_AA:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fas{.gz,}":
          type: file
          description: Aligned sequences in FASTA format. May be gzipped or uncompressed.
          pattern: "*_AA"
          ontologies:
            - edam: http://edamontology.org/format_2554 # ALIGNMENT FORMAT TXT
            - edam: http://edamontology.org/format_1921 # ALIGNMENT FORMAT
            - edam: http://edamontology.org/format_1984 # FASTA-ALN
  versions_macse:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "macse":
          type: string
          description: The name of the tool
      - "macse --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - macse:
          type: string
          description: The name of the tool
      - macse --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@charles-plessy"
maintainers:
  - "@charles-plessy"
