name: "ciri2"
description: Circular RNA identification based on multiple seed matching
keywords:
  - circRNA
  - detection
  - genomics
  - transcriptomics
tools:
  - "ciri2":
      description: "CIRI2: Circular RNA identification based on multiple seed matching"
      homepage: "https://ciri-cookbook.readthedocs.io/en/latest/CIRI2.html"
      documentation: "https://ciri-cookbook.readthedocs.io/en/latest/CIRI2.html"
      tool_dev_url: "https://github.com/bioinfo-biols/CIRI-full/tree/master/bin/CIRI_v2.0.6"
      doi: "10.1093/bib/bbx014"
      licence:
        - "GPL-2.0-only"
      identifier: "biotools:ciri2"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - sam:
        type: file
        description: Raw SAM file from BWA
        pattern: "*.{sam}"
        ontologies:
          - edam: "http://edamontology.org/format_3462"
  - fasta:
      type: file
      description: Fasta file for reference sequence
      pattern: "*.{fasta, fa}"
      ontologies:
        - edam: "http://edamontology.org/format_1929"
  - annotation:
      type: file
      description: GTF or GFF3 annotation file
      pattern: "*.{gtf, gff, gff3}"
      ontologies:
        - edam: "http://edamontology.org/format_2305"
  - ref_dir:
      type: directory
      description: Directory containing reference files
output:
  circrna:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.txt":
          type: file
          description: Output file containing circRNA list
          pattern: "*.{txt}"
      - "CIRIerror.log":
          type: file
          description: Error log file from CIRI2.pl
          pattern: "CIRIerror.log"
  logfile:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.log":
          type: file
          description: Output logfile
          pattern: "*.{log}"
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "CIRI2.pl":
          type: string
          description: The name of the tool used to detect circular RNAs
      - versions:
          type: string
          description: The version of CIRI2.pl used
authors:
  - "@razmia02"
maintainers:
  - "@razmia02"
