name: "dds_createproject"
description: This module is used to create a project on the SciLifeLab Data
  Delivery System (DDS).
keywords:
  - dds
  - scilifelab
  - data delivery
tools:
  - "dds":
      description: "The Data Delivery System (DDS) is a cloud-based system for the delivery
        of data from SciLifeLab platforms to their users."
      homepage: "https://delivery.scilifelab.se"
      documentation: "https://scilifelabdatacentre.github.io/dds_cli/"
      tool_dev_url: "https://github.com/ScilifelabDataCentre/dds_cli"
      licence:
        - "MIT"
      identifier: ""
input:
  - title:
      type: string
      description: The title of the project.
  - description:
      type: string
      description: A description of the project.
  - pi:
      type: string
      description: Email of the Principal Investigator.
output:
  versions_dds:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dds:
          type: string
          description: The name of the tool
      - dds --version:
          type: eval
          description: The expression to obtain the version of the tool
  log:
    - output.log:
        type: file
        description: File containing the projectID of the project created.
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dds:
          type: string
          description: The name of the tool
      - dds --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@annaasklof"
maintainers:
  - "@annaasklof"
