name: "bamreadcount"
description: bam-readcount is a utility that runs on a BAM or CRAM file and
  generates low-level information about sequencing data at specific nucleotide
  positions. Its outputs include observed bases, readcounts, summarized mapping
  and base qualities, strandedness information, mismatch counts, and position
  within the reads.
keywords:
  - BAM
  - CRAM
  - metrics
  - genomics
tools:
  - "bamreadcount":
      description: "bam-readcount generates metrics at single nucleotide positions."
      homepage: "https://github.com/genome/bam-readcount/blob/master/README.md"
      documentation: "https://github.com/genome/bam-readcount/blob/master/README.md"
      tool_dev_url: "https://github.com/genome/bam-readcount"
      doi: "10.21105/joss.03722"
      licence:
        - "MIT"
      identifier: biotools:bam-readcount
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM file
        pattern: "*.{bam,cram}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
          - edam: "http://edamontology.org/format_2573"
    - bai:
        type: file
        description: BAM/CRAM index file
        pattern: "*.{bai,crai}"
        ontologies:
          - edam: "http://edamontology.org/format_2574"
          - edam: "http://edamontology.org/format_2575"
  - reference:
      type: file
      description: Reference genome FASTA file
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
      ontologies:
        - edam: "http://edamontology.org/format_1922"
        - edam: "http://edamontology.org/format_3989"
  - bed:
      type: file
      description: BED file with regions to analyze
      pattern: "*.bed"
      ontologies:
        - edam: "http://edamontology.org/format_1920"
output:
  rc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.rc":
          type: file
          description: Readcount file with metrics
          pattern: "*.rc"
          ontologies: []
  versions_bamreadcount:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bamreadcount:
          type: string
          description: The name of the tool
      - "bam-readcount --version | awk -F'version: ' '{print \\$2}' | awk -F'-' '{print \\$1}'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bamreadcount:
          type: string
          description: The name of the tool
      - "bam-readcount --version | awk -F'version: ' '{print \\$2}' | awk -F'-' '{print \\$1}'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@vmelichar"
maintainers:
  - "@vmelichar"
