name: fastcov
description: Generate a coverage plot from one or more bam files
keywords:
  - coverage
  - bam
  - map
tools:
  - fastcov:
      description: "Generate a coverage plot from one or more bam files"
      homepage: "https://github.com/RaverJay/fastcov/"
      documentation: "https://github.com/RaverJay/fastcov/blob/main/README.md"
      tool_dev_url: "https://github.com/RaverJay/fastcov/tree/main"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: BAM file
        pattern: "*.bam"
        ontologies: []
    - index:
        type: file
        description: BAM index file
        pattern: "*.bai"
        ontologies: []
  - file_ext:
      type: string
      description: output plot file extension string, e.g. `png` or `pdf`
output:
  coverage_plot:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
          pattern: "*.{png,svg,pdf}"
      - ${prefix}.${file_ext}:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
          pattern: "*.{png,svg,pdf}"
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "log.txt":
          type: file
          description: Log output redirected to a text file
          pattern: "log.txt"
          ontologies:
            - edam: "http://edamontology.org/data_1678"
            - edam: "http://edamontology.org/format_2330"
  versions_fastcov:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastcov:
          type: string
          description: The name of the tool
      - "0.1.3":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastcov:
          type: string
          description: The name of the tool
      - "0.1.3":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@davidfischer"
maintainers:
  - "@davidfischer"
