name: sentieon_gvcftyper
description: |
  Perform joint genotyping on one or more samples pre-called with Sentieon's Haplotyper.
keywords:
  - joint genotyping
  - genotype
  - gvcf
tools:
  - sentieon:
      description: |
        Sentieon® provides complete solutions for secondary DNA/RNA analysis for a variety of sequencing platforms, including short and long reads.
        Our software improves upon BWA, STAR, Minimap2, GATK, HaplotypeCaller, Mutect, and Mutect2 based pipelines and is deployable on any generic-CPU-based computing system.
      homepage: https://www.sentieon.com/
      documentation: https://www.sentieon.com/
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - gvcfs:
        type: file
        description: |
          gVCF(.gz) file
        pattern: "*.{vcf,vcf.gz}"
        ontologies: []
    - tbis:
        type: file
        description: |
          index of gvcf file
        pattern: "*.tbi"
        ontologies: []
    - intervals:
        type: file
        description: Interval file with the genomic regions included in the
          library (optional)
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Reference fasta file
        pattern: "*.fasta"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Reference fasta index file
        pattern: "*.fai"
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - dbsnp:
        type: file
        description: dbSNP VCF file
        pattern: "*.vcf.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989
  - - meta5:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - dbsnp_tbi:
        type: file
        description: dbSNP VCF index file
        pattern: "*.tbi"
        ontologies: []
output:
  vcf_gz:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  vcf_gz_tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz.tbi":
          type: file
          description: VCF index file
          pattern: "*.vcf.gz.tbi"
          ontologies: []
  versions_sentieon:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - sentieon:
          type: string
          description: The tool name
      - sentieon driver --version | sed "s/.*-//g":
          type: eval
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - sentieon:
          type: string
          description: The tool name
      - sentieon driver --version | sed "s/.*-//g":
          type: eval
          description: The command used to generate the version of the tool
authors:
  - "@asp8200"
maintainers:
  - "@asp8200"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/sentieon:202503.03--5e34aa16344b911c
      build_id: bd-5e34aa16344b911c_1
      scan_id: sc-8746dd39a4711178_1
    linux/arm64:
      name: community.wave.seqera.io/library/sentieon:202503.03--493a9352fdfbacc5
      build_id: bd-493a9352fdfbacc5_1
      scan_id: sc-cb424814848a20d9_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/sentieon:202503.03--5a01457f1db078c1
      build_id: bd-5a01457f1db078c1_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/af/af478c78e4ddb4fc9c570e47f3d64d86bb02e5c5467c6c095f21f95f59a7c3ab/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/sentieon:202503.03--95eea6ffae22db3c
      build_id: bd-95eea6ffae22db3c_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/2c/2c157e27981ec529b03e7ae5cfc88e51b6158332d2a82db399eef8dd8f2b1d5d/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/sentieon/gvcftyper/.conda-lock/linux_amd64-bd-5e34aa16344b911c_1.txt
    linux/arm64:
      lock_file: modules/nf-core/sentieon/gvcftyper/.conda-lock/linux_arm64-bd-493a9352fdfbacc5_1.txt
