# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/subworkflows/yaml-schema.json
name: "gunzip_fasta_index"
description: Ensure input fasta assemblies are unzipped and indexed, optionally generating a chromosome sizes file.
keywords:
  - index
  - faidx
  - gunzip
  - fasta
components:
  - gunzip
  - gawk
  - samtools/faidx

input:
  - ch_reference:
      type: file
      description: |
        Input fasta reference assembly.

        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{(fasta,fa,fna)(.gz)}"
  - val_sizes:
      type: boolean
      description: |
        Whether to generate a chromosome sizes file from the fasta reference.

output:
  - reference:
      type: file
      description: |
        Input fasta reference assembly.

        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fasta,fa,fna}"
  - fai:
      type: file
      description: |
        SAMTOOLS FASTA index file.

        Structure: [ val(meta), path(fai) ]
      pattern: "*.fai"
  - sizes:
      type: file
      description: |
        Input chromosome sizes file - a TSV with two columns (name and size) and no header line.

        Structure: [ val(meta), path(sizes) ]
      pattern: "*.{sizes,tsv}"

authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
