---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pytinytex=0.5.1
  - quarto=1.9.38
  - r-tinytex=0.60
  - vuegen=0.5.1
  - xz=5.8.1
