name: vuegen
description: >
  The VueGen nf-core module is designed to automate report generation from outputs
  produced by other modules, subworkflows, or pipelines. The module integrates the
  VueGen Python library and customizes it for compatibility with the Nextflow environment.
  VueGen automates the creation of reports from bioinformatics outputs, supporting
  formats
  like PDF, HTML, DOCX, ODT, PPTX, Reveal.js, Jupyter notebooks, and Streamlit web
  applications.
keywords:
  - reports
  - data-visualization
  - streamlit
  - quarto
tools:
  - "vuegen":
      description: >
        The VueGen nf-core module is designed to automate report generation from outputs
        produced by other modules, subworkflows, or pipelines. The module integrates
        the
        VueGen Python library and customizes it for compatibility with the Nextflow
        environment.
        VueGen automates the creation of reports from bioinformatics outputs, supporting
        formats
        like PDF, HTML, DOCX, ODT, PPTX, Reveal.js, Jupyter notebooks, and Streamlit
        web applications.
      homepage: https://github.com/Multiomics-Analytics-Group/vuegen
      documentation: https://vuegen.readthedocs.io/
      tool_dev_url: https://github.com/Multiomics-Analytics-Group/vuegen
      doi: 10.1101/2025.03.05.641152
      licence: ["MIT"]
      identifier: ""
input:
  - input_type:
      type: string
      pattern: "^(config|directory)$"
      description: Specifies whether the input is a configuration file ('config') or a directory ('directory').
  - input_path:
      type: file
      description: Path to the input directory or configuration file used by VueGen.
      ontologies: []
  - report_type:
      type: string
      pattern: "^(streamlit|html|pdf|docx|odt|revealjs|pptx|jupyter)$"
      description: The type of report to generate. Options include 'streamlit', 'html', 'pdf', 'docx', 'odt', 'revealjs', 'pptx', and 'jupyter'.
output:
  output_folder:
    - "*report":
        type: directory
        description: |
          The output directory containing the generated report files.
          - If `report_type` is 'streamlit', a 'streamlit_report' directory is created, containing subfolders for each section with Python scripts corresponding to the web application's pages.
          - For other report types, a 'quarto_report' directory is generated, containing a Quarto Markdown (qmd) file that structures the entire report.
        pattern: "*report"
  versions_vuegen:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vuegen:
          type: string
          description: The name of the tool
      - 'python -c "import vuegen; print(vuegen.__version__)"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vuegen:
          type: string
          description: The name of the tool
      - 'python -c "import vuegen; print(vuegen.__version__)"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@sayalaruano"
  - "@enryH"
  - "@albsantosdel"
maintainers:
  - "@sayalaruano"
  - "@enryH"
  - "@albsantosdel"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pytinytex_quarto_r-tinytex_pruned:b7ae8917d526ebb5
      build_id: bd-b7ae8917d526ebb5_1
      scan_id: sc-4055cafa136aa8e7_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pytinytex_quarto_r-tinytex_pruned:fc2805e0e16a6e6e
      build_id: bd-fc2805e0e16a6e6e_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/2a/2a9cd0a1455ebd911d8621a05ed5a800b32544243e8eaf930cb27998def10bb9/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pytinytex_quarto_r-tinytex_pruned:7c78cdc884f5eaab
      build_id: bd-7c78cdc884f5eaab_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e8/e8f8e5ebb0310052bf80635afb3828e691521d77cbafc522fdf389a1b0f7ab65/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/vuegen/.conda-lock/linux_amd64-bd-b7ae8917d526ebb5_1.txt
