---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::faiss-cpu=1.10.0
  - conda-forge::python=3.10.0
  - pip:
      - caalm==1.0.0
      - torch==2.6.0
