# clustervisualization/environment.yml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::matplotlib=3.9.4
  - conda-forge::numpy=2.4.2
  - conda-forge::pandas=2.2.3
  - conda-forge::python=3.12.12
  - conda-forge::scikit-learn=1.6.1
  - conda-forge::seaborn=0.13.2
  - conda-forge::umap-learn=0.5.12