name: "icountmini_sigxls"
description: Runs iCount sigxls on a BED file of crosslinks
keywords:
  - CLIP
  - iCLIP
  - bed
  - genomics
tools:
  - icount:
      description: Computational pipeline for analysis of iCLIP data
      homepage: https://github.com/ulelab/iCount-Mini
      documentation: https://github.com/ulelab/iCount-Mini
      tool_dev_url: https://github.com/ulelab/iCount-Mini
      doi: "10.1038/nsmb.1838"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: BED file of crosslinks
        pattern: "*.{bam,bam.gz}"
        ontologies: []
  - segmentation:
      type: file
      description: A iCount segmentation file
      pattern: "*.{gtf}"
      ontologies: []
output:
  sigxls:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sigxls.bed.gz":
          type: file
          description: sigxls bed file
          pattern: "*.{bed.gz}"
          ontologies: []
  scores:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.scores.tsv":
          type: file
          description: Crosslink scores calculated by iCount
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions_icount_mini:
    - - ${task.process}:
          type: string
          description: The name of the process
      - iCount-Mini:
          type: string
          description: The name of the tool
      - iCount-Mini -v:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - iCount-Mini:
          type: string
          description: The name of the tool
      - iCount-Mini -v:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@marc-jones"
  - "@chris-cheshire"
  - "@charlotteanne"
maintainers:
  - "@marc-jones"
  - "@chris-cheshire"
  - "@charlotteanne"
