name: "sourmash_pairwise"
description: "Fast, multithreaded comparison of many FracMinHash signatures generated
  by sourmash sketch."
keywords:
  - compare
  - genomics
  - pairwise
  - metagenomics
  - sourmash
  - branchwater
  - kmer
  - containment
tools:
  - "sourmash":
      description: "Quickly search, compare, and analyze genomic and metagenomic data
        sets."
      homepage: "https://sourmash.readthedocs.io/"
      documentation: "https://sourmash.readthedocs.io/"
      tool_dev_url: "https://github.com/sourmash-bio/sourmash"
      doi: "10.21105/joss.00027"
      licence:
        - "BSD-3-clause"
      identifier: biotools:sourmash
  - "sourmash_plugin_branchwater":
      description: "Fast, multithreaded sourmash operations: search, compare, and gather."
      homepage: "https://github.com/sourmash-bio/sourmash_plugin_branchwater"
      documentation: "https://github.com/sourmash-bio/sourmash_plugin_branchwater/blob/main/doc/README.md"
      tool_dev_url: "https://github.com/sourmash-bio/sourmash_plugin_branchwater"
      licence:
        - "AGPL-3.0"
      doi: 10.1101/2022.11.02.514947
      identifier: ""
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information. e.g. [ id:'test',
          single_end:false ]
    - signatures:
        type: file
        description: Files containing signatures (hash sketches) of samples
        pattern: "*.{sig,zip}"
        ontologies:
          - edam: http://edamontology.org/format_3987
  - file_list:
      type: file
      description: An optional file specifying a list of file paths that should be
        appended to the input signatures.
      ontologies: []
output:
  csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*pairwise.csv":
          type: file
          description: Comparisons in long CSV format
          pattern: "*.pairwise.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  versions_sourmash:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sourmash:
          type: string
          description: The name of the tool
      - sourmash --version 2>&1 | sed 's/^sourmash //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sourmash:
          type: string
          description: The name of the tool
      - sourmash --version 2>&1 | sed 's/^sourmash //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@worthyc51"
maintainers:
  - "@worthyc51"
  - "@zachary-foster"
