---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::wget=1.25.0
  - conda-forge::curl=8.18.0
  - bioconda::igblast=1.22.0
  - conda-forge::python=3.12.13
  - pip:
    - torch==2.10.0
    - transformers==4.49.0
    - amulety==2.1.2
