# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_methyldackel"
description: Performs methylation quantification based on negative readout of C to T conversion of 3-letter genome alignments using Methyldackel.
keywords:
  - 3-letter genome
  - methylation
  - 5mC
  - methylseq
  - bisulphite
  - bisulfite
  - bam
components:
  - methyldackel/extract
  - methyldackel/mbias
input:
  - ch_bam:
      type: file
      description: |
        BAM alignment files with index
        Structure: [ val(meta), path(bam), path(bai) ]
      pattern: "*.bam"
  - ch_fasta:
      type: file
      description: |
        Reference genome fasta and index
        Structure: [ val(meta), path(fasta), path(fai) ]
      pattern: "*.{fa,fa.gz}"
output:
  - methydackel_extract_bedgraph:
      type: file
      description: |
        bedGraph file, containing per-base methylation metrics
        Structure: [ val(meta), path(bedgraph) ]
      pattern: "*.bedGraph"
  - methydackel_extract_methylkit:
      type: file
      description: |
        methylKit file, containing per-base methylation metrics
        Structure: [ val(meta), path(methylKit) ]
      pattern: "*.methylKit"
  - methydackel_mbias:
      type: file
      description: |
        Text file containing methylation bias
        Structure: [ val(meta), path(mbias) ]
      pattern: "*.{txt}"
authors:
  - "@eduard-watchmaker"
maintainers:
  - "@eduard-watchmaker"
