name: "smudgeplot_all"
description: Generating smudgeplot k-mer inference plots
keywords:
  - Smudgeplot
  - reference-free
  - kmer
  - plots
tools:
  - "smudgeplot":
      description: "Generating smudgeplot kmer counts"
      homepage: "https://github.com/KamilSJaron/smudgeplot"
      tool_dev_url: "https://github.com/KamilSJaron/smudgeplot"
      licence: ["https://github.com/KamilSJaron/smudgeplot/blob/master/LICENSE.md"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastk_table:
        type: file
        description: Smudgeplot kmer coverage flat file
        pattern: "*.smu"
        ontologies: []

output:
  centrality_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_centralities.png":
          type: file
          description: Smudgeplot centrality plot png
          pattern: "*_centralities.png"
          ontologies:
            - edam: http://edamontology.org/format_3603 # PNG
  smudgeplot_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_smudgeplot.png":
          type: file
          description: Smudgeplot Kmer coverage file
          pattern: "*_smudgeplot.png"
          ontologies:
            - edam: http://edamontology.org/format_3603 # PNG
  log10_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_smudgeplot.png":
          type: file
          description: Smudgeplot Kmer coverage file
          pattern: "*_smudgeplot.png"
          ontologies:
            - edam: http://edamontology.org/format_3603 # PNG
  centrality_txt:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_centralities.txt":
          type: file
          description: Centrality of kmers text file
          pattern: "*_centralities.txt"
          ontologies:
            - edam: http://edamontology.org/format_2330
  smudge_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.smudge_report.tsv":
          type: file
          description: Full smudgeplot report of smudges
          pattern: "*.smudge_report.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  sma:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sma":
          type: file
          description: Smudgeplot Kmer coverage file
          pattern: "*.sma"
          ontologies: []

  versions_smudgeplot:
    - - ${task.process}:
          type: string
          description: Name of the process
      - smudgeplot:
          type: string
          description: The name of the tool
      - smudgeplot -v |& sed "s/.*v//":
          type: string
          description: The expression to obtain the version of the tool
  versions_fastk:
    - - ${task.process}:
          type: string
          description: Name of the process
      - fastk:
          type: string
          description: Name of the tool
      - "1.2":
          type: string
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: Name of the process
      - smudgeplot:
          type: string
          description: The name of the tool
      - smudgeplot -v |& sed "s/.*v//":
          type: string
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: Name of the process
      - fastk:
          type: string
          description: Name of the tool
      - "1.2":
          type: string
          description: The expression to obtain the version of the tool

authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
