name: memote_run
description: Run memote test suite and collect results as JSON
keywords:
  - metabolic model
  - sbml
  - quality control
  - testing
tools:
  - memote:
      description: Benchmark and compare genome-scale metabolic models and generate HTML reports.
      homepage: https://github.com/opencobra/memote
      documentation: https://memote.readthedocs.io/
      tool_dev_url: https://github.com/opencobra/memote
      licence:
        - "Apache-2.0"
      identifier: biotools:memote
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - model:
        type: file
        description: SBML model file.
        pattern: "*.{xml,sbml}"
        ontologies: []
output:
  json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.json.gz":
          type: file
          description: Compressed JSON file containing memote test results.
          pattern: "*.json.gz"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions.
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@brovolia"
maintainers:
  - "@brovolia"
