---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - matplotlib=3.9.*
  - pandas=2.2.*
  - python=3.12
  - scikit-learn=1.5.*
