name: "trnascanse"
description: Detection of tRNA sequences using covariance models
keywords:
  - covariance models
  - trna
  - genome annotation
tools:
  - "trnascanse":
      description: "tRNA detection in large-scale genomic sequences"
      homepage: "http://lowelab.ucsc.edu/tRNAscan-SE/help.html"
      documentation: "http://lowelab.ucsc.edu/tRNAscan-SE/help.html"
      tool_dev_url: "https://github.com/UCSC-LoweLab/tRNAscan-SE"
      doi: "10.1093/nar/gkab688"
      licence:
        - "GPL v3"
        - "GPL v3-or-later"
      identifier: biotools:trnascan-se
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: |
          Fasta file for tRNA annotation. Can be gzipped.
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
          - edam: http://edamontology.org/format_3989 # GZIP format
  - write_stats:
      type: boolean
      description: "Write the stats file"
  - write_fasta:
      type: boolean
      description: "Write a FASTA file of tRNA sequences"
  - write_gff:
      type: boolean
      description: "Write a GFF file of tRNA annotations"
  - write_bed:
      type: boolean
      description: "Write a BED file of tRNA annotations"

output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: TSV summary output of tRNA annotations
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.log":
          type: file
          description: tRNAScan-SE log file
          pattern: "*.log"
          ontologies:
            - edam: http://edamontology.org/data_3671 # Text
  stats:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.stats":
          type: file
          description: Unstructured results file describing tRNA annotations
          pattern: "*.stats"
          ontologies:
            - edam: http://edamontology.org/data_3671 # Text
  fasta:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.fasta":
          type: file
          description: |
            (optional) FASTA output of annotated tRNA sequences
          pattern: "*.fasta.gz"
          ontologies:
            - edam: http://edamontology.org/format_1929 # FASTA
            - edam: http://edamontology.org/format_3989 # GZIP format
  gff:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.gff":
          type: file
          description: |
            (optional) GFF annotation of tRNA sequences in input fasta
          ontologies:
            - edam: "http://edamontology.org/format_1975" # GFF
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed":
          type: file
          description: |
            (optional) BED annotation of tRNA sequences in input fasta
          ontologies:
            - edam: http://edamontology.org/format_3003 # BED
  versions_trnascanse:
    - - ${task.process}:
          type: string
          description: The name of the process
      - tRNAscan-SE:
          type: string
          description: The name of the tool
      - tRNAscan-SE |& sed '2!d;s/tRNAscan-SE //;s/ .*//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - tRNAscan-SE:
          type: string
          description: The name of the tool
      - tRNAscan-SE |& sed '2!d;s/tRNAscan-SE //;s/ .*//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@prototaxites"
maintainers:
  - "@prototaxites"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/trnascan-se_gzip_findutils:b0274a0899088e35
      build_id: bd-b0274a0899088e35_1
      scan_id: sc-90a1a80ff5815a5b_1
    linux/amd64:
      name: community.wave.seqera.io/library/trnascan-se_gzip_findutils:15c0475b13b49f03
      build_id: bd-15c0475b13b49f03_1
      scan_id: sc-56849b20d8e3559a_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/trnascan-se_gzip_findutils:fa05bc72bdec0557
      build_id: bd-fa05bc72bdec0557_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/2a/2ae0c76c670fe400689455bacd48acd58203cf27876fc79b04ed2395681ab7ec/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/trnascan-se_gzip_findutils:7f4fa655dc8e261b
      build_id: bd-7f4fa655dc8e261b_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e6/e67fae15e207274f7007314b675884186eec7d195c82db002cb04cd218f20b8f/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/trnascanse/.conda-lock/linux_amd64-bd-15c0475b13b49f03_1.txt
    linux/arm64:
      lock_file: modules/nf-core/trnascanse/.conda-lock/linux_arm64-bd-b0274a0899088e35_1.txt
