# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "stitchr_thimble"
description: Automatic TCR nucleotide sequence generation from V, J and CDR3 information
keywords:
  - TCR
  - sequence
  - immunology
tools:
  - "stitchr":
      description: "Automatic TCR nucleotide sequence generation from V, J and CDR3 information"
      homepage: "https://github.com/JamieHeather/stitchr"
      documentation: "https://jamieheather.github.io/stitchr/index.html"
      tool_dev_url: "https://github.com/JamieHeather/stitchr"
      doi: "10.1093/nar/gkac190"
      licence: ["MIT"]
      identifier: ""
  - "imgtgenedl":
      description: "provides access to TCR and IG genes stored in IMGT/GENE-DB"
      homepage: "https://github.com/JamieHeather/IMGTgeneDL"
      documentation: "https://github.com/JamieHeather/IMGTgeneDL/blob/main/README.md"
      tool_dev_url: "https://github.com/JamieHeather/IMGTgeneDL"
      doi: "10.1093/nar/gkab1136"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - samplesheet:
        type: file
        description: tsv containing J,V and CDR3 information
        pattern: "*.tsv"
        ontologies: []
    - alt_codon_usage:
        type: file
        description: txt containing alternative codon usage in kazusa-like format
        pattern: "*.txt"
        ontologies: []
    - allele_preferences:
        type: file
        description: tsv containing alternative allele preferences
        pattern: "*.tsv"
        ontologies: []
    - species:
        type: string
        description: Species ("mouse" or "human")

output:
  thimble:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: tsv containing TCR sequence information
          pattern: "*.tsv"
          ontologies: []
  versions_stitchr:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "stitchr":
          type: string
          description: The name of the tool
      - "stitchr --version":
          type: eval
          description: The expression to obtain the version of the tool
  versions_imgtgenedl:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "imgtgenedl":
          type: string
          description: The name of the tool
      - "imgtgenedl --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - stitchr:
          type: string
          description: The name of the tool
      - stitchr --version:
          type: eval
          description: The expression to obtain the version of the tool
      - imgtgenedl:
          type: string
          description: The name of the tool
      - imgtgenedl --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Clara0611"
maintainers:
  - "@Clara0611"
