name: optitype
description: Perform HLA-I typing of sequencing data
keywords:
  - hla-typing
  - ILP
  - HLA-I
tools:
  - optitype:
      description: Precision HLA typing from next-generation sequencing data
      homepage: https://github.com/FRED-2/OptiType
      documentation: https://github.com/FRED-2/OptiType
      doi: "10.1093/bioinformatics/btu548"
      licence:
        - "BSD-3-Clause"
      identifier: biotools:optitype
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM file
        pattern: "*.{bam}"
        ontologies: []
    - bai:
        type: file
        description: BAM index file
        pattern: "*.{bai}"
        ontologies: []
output:
  hla_type:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', seq_type:'DNA' ]
      - ${prefix}/*.tsv:
          type: file
          description: HLA type
          pattern: "${prefix}/*.tsv"
          ontologies: []
  coverage_plot:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', seq_type:'DNA' ]
      - ${prefix}/*.pdf:
          type: file
          description: OptiType coverage plot
          pattern: "${prefix}/*.pdf"
          ontologies: []
  versions_optitype:
    - - ${task.process}:
          type: string
          description: The name of the process
      - optitype:
          type: string
          description: The name of the tool
      - 'optitype info | sed -n "s/.*OptiType version: \([0-9.]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - optitype:
          type: string
          description: The name of the tool
      - 'optitype info | sed -n "s/.*OptiType version: \([0-9.]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@apeltzer"
maintainers:
  - "@apeltzer"
  - "@christopher-mohr"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/optitype_coincbc_cplex:0b46ade42a5009b2
      build_id: bd-0b46ade42a5009b2_1
      scan_id: sc-573b3792bd8c1c1a_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/optitype_coincbc_cplex:740697b2eda2bbc2
      build_id: bd-740697b2eda2bbc2_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/9f/9ff14340c6c903c1c9d926fb7ffa60460986852515c76673cc54f6c958ff35bd/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/optitype/.conda-lock/linux_amd64-bd-0b46ade42a5009b2_1.txt
