# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_markduplicates_samtools"
description: Samtools markduplicate SAM/BAM/CRAM file
keywords:
  - markdup
  - bam
  - sam
  - cram
components:
  - samtools/collate
  - samtools/fixmate
  - samtools/sort
  - samtools/markdup
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - fasta_fai:
      type: file
      description: FASTA file and index
      pattern: "*.{fasta,fa,fai}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`
  - bam:
      type: file
      description: Sorted and markduplicate BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
authors:
  - "@priyanka-surana"
maintainers:
  - "@priyanka-surana"
