name: modkit_localize
description: Investigate patterns of base modifications by aggregating pileup counts localized around genomic features of interest
keywords:
  - methylation
  - ont
  - long-read
  - localize
  - enrichment
tools:
  - "modkit":
      description: A bioinformatics tool for working with modified bases in Oxford
        Nanopore sequencing data
      homepage: https://github.com/nanoporetech/modkit
      documentation: https://github.com/nanoporetech/modkit
      tool_dev_url: https://github.com/nanoporetech/modkit
      licence: ["Oxford Nanopore Technologies PLC. Public License Version 1.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - bedmethyl:
        type: file
        description: bgzip-compressed bedMethyl file from modkit pileup
        pattern: "*.bed.gz"
        ontologies: []
    - tbi:
        type: file
        description: Tabix index for the bedMethyl file
        pattern: "*.bed.gz.tbi"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing genome sizes information
          e.g. `[ id:'hg38' ]`
    - sizes:
        type: file
        description: TSV of genome sizes with columns chrom and size_in_bp
        pattern: "*.{sizes,tsv,txt,genome}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing regions BED file information
          e.g. `[ id:'CpG_islands' ]`
    - regions:
        type: file
        description: |
          BED file of regions to calculate enrichment around. These serve
          as the points from which the window number of bases is centered
          (e.g. CpG islands, gene bodies, repeat elements).
        pattern: "*.bed"
        ontologies: []
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.tsv":
          type: file
          description: TSV output with percent-modification vs. offset from feature midpoints
          pattern: "*.tsv"
          ontologies: []
  chart:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.html":
          type: file
          description: HTML document with interactive chart showing percent-modification
            vs. offset
          pattern: "*.html"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.log":
          type: file
          description: File for debug logs to be written to
          pattern: "*.log"
          ontologies: []
  versions_modkit:
    - - ${task.process}:
          type: string
          description: The name of the process
      - modkit:
          type: string
          description: The name of the tool
      - modkit --version | sed 's/modkit //':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - modkit:
          type: string
          description: The name of the tool
      - modkit --version | sed 's/modkit //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@sahuno"
maintainers:
  - "@sahuno"
