name: "fastdup"
description: "FastDup is a tool designed to locate and tag duplicate reads in a coordinate-sorted
  SAM or BAM file, using the same core algorithm as Picard MarkDuplicates."
keywords:
  - duplicate
  - BAM
  - reads
tools:
  - "fastdup":
      description: "FastDup is a tool designed to locate and tag duplicate reads in
        a coordinate-sorted SAM or BAM file, using the same core algorithm as Picard
        MarkDuplicates."
      homepage: "https://github.com/zzhofict/FastDup"
      documentation: "https://github.com/zzhofict/FastDup"
      tool_dev_url: "https://github.com/zzhofict/FastDup"
      doi: "10.1093/bioinformatics/btaf633"
      licence:
        - "MIT"
      identifier: "biotools:fastdup"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reads:
        type: file
        description: Sequence reads file, can be SAM/BAM format
        pattern: "*.{bam,sam}"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: BAM file with duplicate reads marked/removed.
          pattern: "*.{bam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572"
  versions_fastdup:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastdup:
          type: string
          description: The name of the tool
      - fastdup --version:
          type: eval
          description: The expression to obtain the version of the tool
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.metrics.txt":
          type: file
          description: Duplicate metrics file generated by fastdup.
          pattern: "*.{metrics.txt}"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bai":
          type: file
          description: BAI index file generated by fastdup.
          pattern: "*.{bai}"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.csi":
          type: file
          description: CSI index file generated by fastdup.
          pattern: "*.{csi}"
          ontologies: []
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastdup:
          type: string
          description: The name of the tool
      - fastdup --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@emmadizdarevic"
maintainers:
  - "@emmadizdarevic"
