name: "deepcell_mesmer"
description: Deepcell/mesmer segmentation for whole-cell
keywords:
  - imaging
  - spatial_omics
  - segmentation
tools:
  - "mesmer":
      description: "Deep cell is a collection of tools to segment imaging data"
      homepage: "https://github.com/vanvalenlab/deepcell-tf"
      documentation: "https://github.com/vanvalenlab/intro-to-deepcell/tree/master/pretrained_models"
      tool_dev_url: "https://githu/b.com/vanvalenlab/deepcell-tf"
      doi: 10.1038/s41587-021-01094-0
      licence:
        - "APACHE2"
      identifier: biotools:deepcell
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - img:
        type: file
        description: Multichannel image file
        pattern: "*.{tiff,tif,h5,hdf5}"
        ontologies:
          - edam: http://edamontology.org/format_3590 # HDF5
          - edam: http://edamontology.org/format_3591 # TIFF
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - membrane_img:
        type: file
        description: Optional membrane image to be provided separately.
        pattern: "*.{tiff,tif,h5,hdf5}"
        ontologies:
          - edam: http://edamontology.org/format_3590 # HDF5
          - edam: http://edamontology.org/format_3591 # TIFF
output:
  mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tif":
          type: file
          description: File containing the mask.
          pattern: "*.{tif, tiff}"
          ontologies:
            - edam: http://edamontology.org/format_3591 # TIFF
  versions_mesmer:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deepcell_mesmer:
          type: string
          description: The name of the tool
      - 0.4.1:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deepcell_mesmer:
          type: string
          description: The name of the tool
      - 0.4.1:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@migueLib"
  - "@chiarasch"
maintainers:
  - "@migueLib"
  - "@chiarasch"
