# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: fastq_align_bowtie2
description: Align reads to a reference genome using bowtie2 then sort with samtools
keywords:
  - align
  - fasta
  - genome
  - reference
components:
  - bowtie2/align
  - samtools/sort
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_sort_stats_samtools
input:
  - ch_reads:
      type: file
      description: |
        Channel containing a list of input FastQ files of size 1 and 2 for single-end
        and paired-end data, respectively.

        Structure: [ val(meta), [ path(reads) ] ]
      pattern: "*.fastq.gz"
  - ch_index:
      type: file
      description: |
        Channel containing the Bowtie2 genome index directory.

        Structure: [ val(meta2), path(index) ]
  - save_unaligned:
      type: boolean
      description: |
        Save reads that do not map to the reference (true) or discard them (false)
        (default: false)
  - sort_bam:
      type: boolean
      description: |
        Use samtools sort (true) or samtools view (false)
      default: false
  - ch_fasta_fai:
      type: file
      description: |
        Channel containing the reference fasta file and its index.

        Structure: [ val(meta3), path(fasta), path(fai) ]
output:
  - bam_orig:
      type: file
      description: |
        BAM file straight out of Bowtie2, before sorting.

        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - log_out:
      type: file
      description: |
        Bowtie2 alignment log.

        Structure: [ val(meta), path(log) ]
      pattern: "*.log"
  - fastq:
      type: file
      description: |
        Unaligned FastQ files, emitted when `save_unaligned` is true.

        Structure: [ val(meta), [ path(fastq) ] ]
      pattern: "*.fastq.gz"
  - bam:
      type: file
      description: |
        Sorted BAM file containing read alignments.

        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - index:
      type: file
      description: |
        Index for the sorted BAM file.

        Structure: [ val(meta), path(index) ]
      pattern: "*.{bai,csi,crai}"
  - stats:
      type: file
      description: |
        File containing samtools stats output.

        Structure: [ val(meta), path(stats) ]
      pattern: "*.stats"
  - flagstat:
      type: file
      description: |
        File containing samtools flagstat output.

        Structure: [ val(meta), path(flagstat) ]
      pattern: "*.flagstat"
  - idxstats:
      type: file
      description: |
        File containing samtools idxstats output.

        Structure: [ val(meta), path(idxstats) ]
      pattern: "*.idxstats"
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
