name: flash
description: Perform merging of mate paired-end sequencing reads
keywords:
  - sort
  - reads merging
  - merge mate pairs
tools:
  - flash:
      description: |
        Merge mates from fragments that are shorter than twice the read length
      homepage: https://ccb.jhu.edu/software/FLASH/
      doi: 10.1093/bioinformatics/btr507
      licence:
        - "GPL v3+"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 2; i.e., paired-end data.
        pattern: "*fastq.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989
output:
  merged:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.extendedFrags.fastq.gz:
          type: file
          description: The merged fastq reads
          pattern: ".extendedFrags.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  notcombined:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.notCombined_*.fastq.gz:
          type: file
          description: Not combined reads from flash
          pattern: ".notCombined_*.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  histogram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.hist:
          type: file
          description: HistogramNumeric histogram of merged read lengths.
          pattern: ".hist"
          ontologies: []
  versions_flash:
    - - ${task.process}:
          type: string
          description: The name of the process
      - flash:
          type: string
          description: The name of the tool
      - echo $(flash --version 2>&1) | sed 's/^.*FLASH v//; s/ .*$//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - flash:
          type: string
          description: The name of the tool
      - echo $(flash --version 2>&1) | sed 's/^.*FLASH v//; s/ .*$//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Erkison"
maintainers:
  - "@Erkison"
