name: "gvcftools_extractvariants"
description: Removes all non-variant blocks from a gVCF file to produce a
  smaller variant-only VCF file.
keywords:
  - gvcftools
  - extract_variants
  - extractvariants
  - gvcf
  - vcf
tools:
  - "gvcftools":
      description: "gvcftools is a package of small utilities for creating and analyzing
        gVCF files"
      homepage: "https://sites.google.com/site/gvcftools/home"
      documentation: "https://sites.google.com/site/gvcftools/home/configuration-and-analysis"
      tool_dev_url: "https://github.com/sequencing/gvcftools"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - gvcf:
        type: file
        description: GVCF file
        pattern: "*.{g.vcf,gvcf}.gz"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: Converted variant-only VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP
  versions_gvcftools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gvcftools:
          type: string
          description: The name of the tool
      - "extract_variants --help 2>&1 | sed -n 's/version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gvcftools:
          type: string
          description: The name of the tool
      - "extract_variants --help 2>&1 | sed -n 's/version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
