name: eider_querytoparquet
description: Generic DuckDB query to Parquet format
keywords:
  - duckdb
  - parquet
  - sql
  - query
tools:
  - eider:
      description: |
        Command line bioinformatics tools for DuckDB.
      homepage: https://github.com/heuermh/eider
      documentation: https://github.com/heuermh/eider
      licence: ["Apache-2.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - sql:
        type: file
        description: SQL query template
        pattern: "*.{sql|sql.bgz|sql.gz|sql.zst}"
output:
  parquet:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.parquet":
          type: file
          description: |
            Query results in Parquet format
          pattern: "*.{parquet}"
          ontologies: []
  versions_eider:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - eider:
          type: string
          description: The tool name
      - "eider --version 2>&1 | grep -o 'eider .*' | cut -f2 -d ' '":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - eider:
          type: string
          description: The tool name
      - "eider --version 2>&1 | grep -o 'eider .*' | cut -f2 -d ' '":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@heuermh"
maintainers:
  - "@heuermh"
