name: "cowpy"
description: Print any text in a cow or other characters
keywords:
  - cowpy
  - hello
  - ascii_art
tools:
  - "cowpy":
      description: "Print any text in a cow or other characters"
      homepage: "https://github.com/jeffbuttars/cowpy"
      documentation: "https://github.com/jeffbuttars/cowpy"
      tool_dev_url: "https://github.com/jeffbuttars/cowpy"
      licence:
        - "Apache-2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - text:
        type: file
        description: text file
        pattern: "*.{txt}"
        ontologies: []
output:
  txt:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.txt"
      - ${prefix}.txt:
          type: file
          description: test file
          pattern: "*.txt"
          ontologies: []
  versions_cowpy:
    - - ${task.process}:
          type: string
          description: The name of the process
      - cowpy:
          type: string
          description: The name of the tool
      - 1.1.5:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - cowpy:
          type: string
          description: The name of the tool
      - 1.1.5:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
