name: pairix
description: |
  a tool for indexing and querying on a block-compressed text file
  containing pairs of genomic coordinates
keywords:
  - index
  - block-compressed
  - pairs
tools:
  - pairix:
      description: 2D indexing on bgzipped text files of paired genomic
        coordinates
      homepage: "https://github.com/4dn-dcic/pairix"
      documentation: "https://github.com/4dn-dcic/pairix"
      tool_dev_url: "https://github.com/4dn-dcic/pairix"
      licence:
        - "MIT"
      identifier: biotools:pairix
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - pair:
        type: file
        description: pair file
        ontologies: []
output:
  index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - pair:
          type: file
          description: pair index file
          pattern: "*.px2"
          ontologies: []
      - "*.px2":
          type: file
          description: pair index file
          pattern: "*.px2"
          ontologies: []
  versions_pairix:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pairix:
          type: string
          description: The name of the tool
      - 'echo $(pairix --help 2>&1) | sed "s/^.*Version: //; s/Usage.*$//"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pairix:
          type: string
          description: The name of the tool
      - 'echo $(pairix --help 2>&1) | sed "s/^.*Version: //; s/Usage.*$//"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@jianhong"
maintainers:
  - "@jianhong"
