---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fgumi=0.1.2
  - conda-forge::r-base=4.5.3
  - conda-forge::r-ggplot2=4.0.2
  - conda-forge::r-scales=1.4.0
