name: huggingface_download
description: Command-line interface for downloading models in GGUF format from Hugging Face Hub
keywords:
  - ai
  - gguf
  - llama
  - llm
tools:
  - huggingface_hub:
      description: "Command-line interface for interacting with Hugging Face Hub, allowing to download, upload and interact with models and datasets"
      homepage: "https://huggingface.co/docs/huggingface_hub/guides/cli"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`- prompt_file:
    - hf_repo:
        type: string
        description: Hugging Face repository
    - hf_file:
        type: string
        description: Hugging Face GGUF file
    - hf_home:
        type: string
        description: Hugging Face default cache directory
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - hf_file:
          type: file
          description: Downloaded Hugging Face GGUF file
          ontologies: []
  versions_huggingface_hub:
    - - ${task.process}:
          type: string
          description: The name of the process
      - huggingface_hub:
          type: string
          description: The name of the tool
      - hf --version 2>&1 | tail -n1 | awk '{print \$NF}':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - huggingface_hub:
          type: string
          description: The name of the tool
      - hf --version 2>&1 | tail -n1 | awk '{print \$NF}':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@toniher"
  - "@lucacozzuto"
maintainers:
  - "@toniher"
  - "@lucacozzuto"
