name: "shinyngs_app"
description: build and deploy Shiny apps for interactively mining differential abundance data
keywords:
  - differential
  - expression
  - rna-seq
  - deseq2
tools:
  - "shinyngs":
      description: "Provides Shiny applications for various array and NGS applications. Currently very RNA-seq centric, with plans for expansion."
      homepage: "https://github.com/pinin4fjords/shinyngs"
      documentation: "https://rawgit.com/pinin4fjords/shinyngs/master/vignettes/shinyngs.html"
      tool_dev_url: "https://github.com/pinin4fjords/shinyngs"
      licence: ["AGPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing information on experiment, at a minimum an id.
          e.g. [ id:'test' ]
    - sample:
        type: file
        description: |
          CSV-format sample sheet with sample metadata
        ontologies: []
    - feature_meta:
        type: file
        description: |
          TSV-format feature (e.g. gene) metadata
        ontologies: []
    - assay_files:
        type: file
        description: |
          List of TSV-format matrix files representing different measures for the same samples (e.g. raw and normalised).
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing information on experiment, at a minimum an id. To match meta.
          e.g. [ id:'test' ]
    - contrasts:
        type: file
        description: |
          CSV-format file with four columns identifying the sample sheet variable, reference level, treatment level, and optionally a comma-separated list of covariates used as blocking factors.
        ontologies: []
    - differential_results:
        type: file
        description: |
          List of TSV-format differential analysis outputs, one per row of the contrasts file
        ontologies: []
  - contrast_stats_assay:
      type: file
      description: contrast statistics
      ontologies: []
output:
  app:
    - - meta:
          type: map
          description: |
            Groovy Map containing information on experiment.
            e.g. [ id:'test' ]
      - "*/data.rds":
          type: file
          description: |
            The mini R script required build an application from data.rds.
          pattern: "app/app.R"
          ontologies:
            - edam: http://edamontology.org/format_3999 # R script
      - "*/app.R":
          type: file
          description: |
            The mini R script required build an application from data.rds.
          pattern: "app/app.R"
          ontologies:
            - edam: http://edamontology.org/format_3999 # R script
  versions_shinyngs:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/r-shinyngs:3.1.1--b5595b301bfbfd4d
      build_id: bd-b5595b301bfbfd4d_2
      scan_id: sc-73b4cbdd1930464e_1
    linux/arm64:
      name: community.wave.seqera.io/library/r-shinyngs:3.1.1--4d71a4d10942e43f
      build_id: bd-4d71a4d10942e43f_2
      scan_id: sc-72596f6b93ff3200_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.1.1--791778d7e2758322
      build_id: bd-791778d7e2758322_2
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8a/8acde9b0bc0374d51ca50f3e49fb0f26a6fb394d277b3af5e276de8bf1786610/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.1.1--60831a2d7cd7ae94
      build_id: bd-60831a2d7cd7ae94_2
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/6f/6fff209824ab2042c6f09b68d257d59ae4e0ea7410dad923089db9c5c0dbd683/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/shinyngs/app/.conda-lock/linux_amd64-bd-b5595b301bfbfd4d_2.txt
    linux/arm64:
      lock_file: modules/nf-core/shinyngs/app/.conda-lock/linux_arm64-bd-4d71a4d10942e43f_2.txt
