---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pybiolib=1.1.1393
  - conda-forge::click=8.0.3
  - conda-forge::python=3.12.0
  - conda-forge::setuptools=68.2.2
