name: "bioawk"
description: Bioawk is an extension to Brian Kernighan's awk, adding the support
  of several common biological data formats.
keywords:
  - bioawk
  - fastq
  - fasta
  - sam
  - file manipulation
  - awk
tools:
  - bioawk:
      description: BWK awk modified for biological data
      homepage: https://github.com/lh3/bioawk
      documentation: https://github.com/lh3/bioawk
      tool_dev_url: https://github.com/lh3/bioawk
      licence:
        - Free software license
          (https://github.com/lh3/bioawk/blob/master/README.awk#L1)
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: |
          Input biological sequence file (optionally gzipped) to be manipulated via the program specified in `$args`.
        pattern: "*.{bed,gff,sam,vcf,fastq,fasta,tab,bed.gz,gff.gz,sam.gz,vcf.gz,fastq.gz,fasta.gz,tab.gz}"
        ontologies:
          - edam: http://edamontology.org/format_1930
          - edam: http://edamontology.org/format_3475
  - suffix:
      type: string
      description: The suffix to add to the output file name.
  - zip_bool:
      type: boolean
      description: Whether to gzip the output file.
      pattern: "true|false"
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${file_output}:
          type: file
          description: Manipulated version of the input sequence file.
          ontologies: []
  gz_output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gz":
          type: file
          description: Manipulated and gzipped version of the input sequence file.
          pattern: "*.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_bioawk:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioawk:
          type: string
          description: The name of the tool
      - "1.0":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioawk:
          type: string
          description: The name of the tool
      - "1.0":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
schema_version: 1.1.0
