FROM nanoporetech/dorado:shac8f356489fa8b44b31beba841b84d2879de2088e

LABEL version="1.4.0" \
      maintainer="@sahuno" \
      description="Oxford Nanopore dorado basecaller v1.4.0 — for nf-core/modules" \
      org.opencontainers.image.version="1.4.0" \
      org.opencontainers.image.source="https://github.com/nanoporetech/dorado" \
      org.opencontainers.image.licenses="Oxford Nanopore Technologies PLC. Public License Version 1.0"
