---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::svtyper=0.7.1
  - conda-forge::python=2.7
  - conda-forge::setuptools=44.0.0
