name: "chopper"
description: Filter and trim long read data.
keywords:
  - filter
  - trimming
  - fastq
  - nanopore
  - qc
tools:
  - "pigz":
      description: "A parallel implementation of gzip for modern multi-processor, multi-core machines."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"
      tool_dev_url: "https://github.com/madler/pigz"
      args_id:
        - "args"
        - "args3"
      identifier: ""
  - "chopper":
      description: "A rust command line for filtering and trimming long reads."
      homepage: "https://github.com/wdecoster/chopper"
      documentation: "https://github.com/wdecoster/chopper"
      tool_dev_url: "https://github.com/wdecoster/chopper"
      doi: "10.1093/bioinformatics/bty149"
      licence:
        - "MIT"
      args_id: "$args2"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: FastQ with reads from long read sequencing e.g. PacBio or ONT
        pattern: "*.{fastq.gz}"
        ontologies: []
  - fasta:
      type: file
      description: An optional reference fasta file against which to remove reads that align to it.
      pattern: "*.fasta"
      ontologies: []
output:
  fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fastq.gz":
          type: file
          description: Filtered and trimmed FastQ file
          pattern: "*.{fastq.gz}"
          ontologies: []
  versions_chopper:
    - - ${task.process}:
          type: string
          description: The name of the process
      - chopper:
          type: string
          description: The name of the tool
      - "chopper --version 2>&1 | cut -d ' ' -f 2":
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool used for compression / decompression
      - pigz --version | sed 's/pigz //g':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - chopper:
          type: string
          description: The name of the tool
      - "chopper --version 2>&1 | cut -d ' ' -f 2":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - "pigz --version | sed 's/pigz //g'":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@FynnFreyer"
  - "@OlivierCoen"
maintainers:
  - "@FynnFreyer"
