name: kraken2_add
description: Adds fasta files to a Kraken2 taxonomic database
keywords:
  - metagenomics
  - db
  - classification
  - build
  - kraken2
  - add
tools:
  - kraken2:
      description: "Kraken2 is a system for assigning taxonomic labels to short DNA sequences, usually obtained through metagenomic studies."
      homepage: https://ccb.jhu.edu/software/kraken2/
      documentation: https://github.com/DerrickWood/kraken2/wiki/Manual
      tool_dev_url: "https://github.com/DerrickWood/kraken2"
      doi: 10.1186/s13059-019-1891-0
      publication:
        author: "Wood D.E., Lu J. & Langmead B."
        year: 2019
        title: "Improved metagenomic analysis with Kraken 2"
        source: "Genome Biology"
      licence:
        - "MIT"
      identifier: biotools:kraken2
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: fasta file that will be added to the database
        pattern: "*.{fa,fasta,fna,ffn}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - taxonomy_names:
      type: file
      description: used for associating sequences with taxonomy IDs
      pattern: "*.dmp"
      ontologies:
        - edam: http://edamontology.org/data_3028
  - taxonomy_nodes:
      type: file
      description: tree nodes using NCBI taxonomy nomenclature
      pattern: "*.dmp"
      ontologies:
        - edam: http://edamontology.org/data_3028 # Taxonomy
  - accession2taxid:
      type: file
      description: associates sequence accession IDs to taxonomy IDs
      pattern: "*.accession2taxid"
      ontologies:
        - edam: http://edamontology.org/data_3028 # Taxonomy
  - seqid2taxid:
      type: file
      description: optional premade 2 column seq2taxid map file. Must be named seq2taxid.map. If not supplied will be generated by kraken2 itself during upstream build step.
      pattern: "seqid2taxid.map"
      ontologies:
        - edam: http://edamontology.org/data_3028 # Taxonomy
output:
  library_added_files:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*/"
      - ${prefix}/library/added/*:
          type: file
          description: Files present in the <name>/library/added/ directory, including FASTA files, masked FASTAs, and prelim_map files.
          pattern: "*"
          ontologies:
            - edam: http://edamontology.org/format_1929 # FASTA
  seqid2taxid_map:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*/"
      - ${prefix}/seqid2taxid.map:
          type: file
          description: File mapping sequence IDs to taxonomy IDs, either generated or premade.
          pattern: "seqid2taxid.map"
          ontologies:
            - edam: http://edamontology.org/data_3028 # Taxonomy
  taxonomy_files:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*/"
      - ${prefix}/taxonomy/*:
          type: file
          description: Files present in the <name>/taxonomy/ directory, including nodes.dmp, names.dmp, and .accession2taxid files.
          pattern: "*"
          ontologies:
            - edam: http://edamontology.org/data_3028 # Taxonomy
  versions_kraken2:
    - - ${task.process}:
          type: string
          description: The name of the process
      - kraken2:
          type: string
          description: The name of the tool
      - kraken2 --version 2>&1 | head -1 | sed "s/^.*Kraken version //; s/ .*//":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - kraken2:
          type: string
          description: The name of the tool
      - kraken2 --version 2>&1 | head -1 | sed "s/^.*Kraken version //; s/ .*//":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@alxndrdiaz"
maintainers:
  - "@alxndrdiaz"
  - "@jfy133"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/kraken2_coreutils_pigz:b111fc3860b64b23
      build_id: bd-b111fc3860b64b23_1
      scan_id: sc-6976dfb99f2bfdc4_1
    linux/arm64:
      name: community.wave.seqera.io/library/kraken2_coreutils_pigz:7d7b46e5b5cc0202
      build_id: bd-7d7b46e5b5cc0202_1
      scan_id: sc-d9823d3c8ed09ebf_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/kraken2_coreutils_pigz:6647bf0cf5a34e5b
      build_id: bd-6647bf0cf5a34e5b_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/ec/ec5af88da27c32c52b667af2af67ce76ffc96715c1a40e0f4ab72dd87623adfa/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/kraken2_coreutils_pigz:2e813a040b8167c6
      build_id: bd-2e813a040b8167c6_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/7c/7c9e4afffe492bf3766631f44c6e04530859d124fb1bc7962ca734abbf63d0b4/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/kraken2/add/.conda-lock/linux_amd64-bd-b111fc3860b64b23_1.txt
    linux/arm64:
      lock_file: modules/nf-core/kraken2/add/.conda-lock/linux_arm64-bd-7d7b46e5b5cc0202_1.txt
