channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fusion-inspector=2.11.5
  - bioconda::igv-reports=1.16.0
  - bioconda::perl-json-xs=4.03
  - bioconda::pysam=0.24.0
  - conda-forge::perl-carp-assert=0.21
  - conda-forge::pip==26.1.1
  - pip:
      - intervaltree==3.2.1
