name: "shinyngs_staticdifferential"
description: Make plots for interpretation of differential abundance statistics
keywords:
  - rnaseq
  - plot
  - differential
  - shinyngs
tools:
  - "shinyngs":
      description: "Provides Shiny applications for various array and NGS applications. Currently very RNA-seq centric, with plans for expansion."
      homepage: "https://github.com/pinin4fjords/shinyngs"
      documentation: "https://rawgit.com/pinin4fjords/shinyngs/master/vignettes/shinyngs.html"
      tool_dev_url: "https://github.com/pinin4fjords/shinyngs"
      licence: ["AGPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing contrast information, to be passed as reference
          and target levels, like '--reference_level $meta.reference
          --treatment_level $meta.target'
          e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
    - differential_result:
        type: file
        description: statistic differential results
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing information on experiment represented by max,
          features and samples, at a minimum an id.
          e.g. [ id:'test' ]
    - sample:
        type: file
        description: |
          CSV or TSV-format sample sheet with sample metadata
        ontologies: []
    - feature_meta:
        type: file
        description: |
          CSV or TSV-format feature (e.g. gene) metadata
        ontologies: []
    - assay_file:
        type: file
        description: |
          CSV or TSV matrix file to use alongside differential statistics in
          interpretation. Usually a normalised form.
        ontologies: []
output:
  volcanos_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing contrast information
            e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
      - "*/png/volcano.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG output for a volcano plot built from
            the differential result table.
          ontologies: []
  volcanos_html:
    - - meta:
          type: map
          description: |
            Groovy Map containing contrast information
            e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
      - "*/html/volcano.html":
          type: file
          description: |
            Meta-keyed tuple containing an HTML output for a volcano plot built
            from the differential result table.
          ontologies: []
  versions_shinyngs:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/r-shinyngs:3.2.0--71dbb9a6ee95bc28
      build_id: bd-71dbb9a6ee95bc28_1
      scan_id: sc-0b57ec15282cc0fe_1
    linux/amd64:
      name: community.wave.seqera.io/library/r-shinyngs:3.2.0--19cca4636e20b0f7
      build_id: bd-19cca4636e20b0f7_1
      scan_id: sc-501add0467d2f061_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.2.0--c8c7c602b7ecaf69
      build_id: bd-c8c7c602b7ecaf69_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/41/41759558393509662940440e609bd5e89e4ec0d4b02c09421923fa0270926666/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.2.0--537d87067431146d
      build_id: bd-537d87067431146d_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/a0/a0bd003b3b7ca7b4081291d4b2cf34b41afb8cf1dd18ffb6f3c7134aaa00c7df/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/shinyngs/staticdifferential/.conda-lock/linux_amd64-bd-19cca4636e20b0f7_1.txt
    linux/arm64:
      lock_file: modules/nf-core/shinyngs/staticdifferential/.conda-lock/linux_arm64-bd-71dbb9a6ee95bc28_1.txt
