name: "shinyngs_staticdifferential"
description: Make plots for interpretation of differential abundance statistics
keywords:
  - rnaseq
  - plot
  - differential
  - shinyngs
tools:
  - "shinyngs":
      description: "Provides Shiny applications for various array and NGS applications. Currently very RNA-seq centric, with plans for expansion."
      homepage: "https://github.com/pinin4fjords/shinyngs"
      documentation: "https://rawgit.com/pinin4fjords/shinyngs/master/vignettes/shinyngs.html"
      tool_dev_url: "https://github.com/pinin4fjords/shinyngs"
      licence: ["AGPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing contrast information, to be passed as reference
          and target levels, like '--reference_level $meta.reference
          --treatment_level $meta.target'
          e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
    - differential_result:
        type: file
        description: statistic differential results
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing information on experiment represented by max,
          features and samples, at a minimum an id.
          e.g. [ id:'test' ]
    - sample:
        type: file
        description: |
          CSV or TSV-format sample sheet with sample metadata
        ontologies: []
    - feature_meta:
        type: file
        description: |
          CSV or TSV-format feature (e.g. gene) metadata
        ontologies: []
    - assay_file:
        type: file
        description: |
          CSV or TSV matrix file to use alongside differential statistics in
          interpretation. Usually a normalised form.
        ontologies: []
output:
  volcanos_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing contrast information
            e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
      - "*/png/volcano.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG output for a volcano plot built from
            the differential result table.
          ontologies: []
  volcanos_html:
    - - meta:
          type: map
          description: |
            Groovy Map containing contrast information
            e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
      - "*/html/volcano.html":
          type: file
          description: |
            Meta-keyed tuple containing an HTML output for a volcano plot built
            from the differential result table.
          ontologies: []
  versions_shinyngs:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/r-shinyngs:3.2.1--d43071e62bc500d3
      build_id: bd-d43071e62bc500d3_1
      scan_id: sc-5ac2dcb847246bad_1
    linux/arm64:
      name: community.wave.seqera.io/library/r-shinyngs:3.2.1--d168a374ce5dc1af
      build_id: bd-d168a374ce5dc1af_1
      scan_id: sc-0f3dfab20873614f_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.2.1--b810af5b9efbb4b2
      build_id: bd-b810af5b9efbb4b2_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/d5/d5f79ef0afe3e3831496c61c81aeda56312f49ac324dc378d3312af7acae2ec6/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.2.1--ed7d3904b821c0a8
      build_id: bd-ed7d3904b821c0a8_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/74/74ebb0b4cfa12e1174262987ffa0559ab388198ba94196a4fd295ce5a9051a22/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/shinyngs/staticdifferential/.conda-lock/linux_amd64-bd-d43071e62bc500d3_1.txt
    linux/arm64:
      lock_file: modules/nf-core/shinyngs/staticdifferential/.conda-lock/linux_arm64-bd-d168a374ce5dc1af_1.txt
