---
name: "mat2json"
description: converst matlab .mat files into json or csv files.
keywords:
  - file conversion
  - matlab
  - json
  - csv
tools:
  - "mat2json":
      description: "Converts matlab .mat files into json or csv files."
      homepage: "https://github.com/qbic-pipelines/mat2json"
      documentation: "https://github.com/qbic-pipelines/mat2json/blob/main/README.md"
      tool_dev_url: "https://github.com/qbic-pipelines/mat2json"
      licence: ["MIT"]
      identifier:

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`

    - mat_file:
        type: file
        description: matlab file
        pattern: "*.{mat}"

output:
  - converted_file:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`

      - "*_conv.*":
          type: file
          description: JSON or CSV file containing the the data from the input .mat file
          pattern: "*.{json,csv}"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@CaroAMN"
maintainers:
  - "@CaroAMN"
