name: "plink_checksex"
description: Estimate genetic sex from X chromosome homozygosity and Y chromosome genotype counts and report discrepancies with reported sex
keywords:
  - plink
  - check-sex
  - sex chromosome
  - quality control
tools:
  - "plink":
      description: "Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner."
      homepage: "https://www.cog-genomics.org/plink"
      documentation: "https://www.cog-genomics.org/plink/1.9/basic_stats#check_sex"
      tool_dev_url: "https://www.cog-genomics.org/plink/1.9/dev"
      licence:
        - "GPL"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: PLINK binary biallelic genotype table file
        pattern: "*.{bed}"
        ontologies: []
    - bim:
        type: file
        description: PLINK extended MAP file
        pattern: "*.{bim}"
        ontologies: []
    - fam:
        type: file
        description: PLINK sample information file
        pattern: "*.{fam}"
        ontologies: []
output:
  sexcheck:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sexcheck":
          type: file
          description: Per-sample sex check report comparing pedigree sex to genetically imputed sex
          pattern: "*.{sexcheck}"
          ontologies: []
  versions_plink:
    - - "${task.process}":
          type: string
          description: The name of the process
      - plink:
          type: string
          description: The name of the tool
      - "plink --version 2>&1 | sed 's/^PLINK v//;s/ .*//'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - plink:
          type: string
          description: The name of the tool
      - "plink --version 2>&1 | sed 's/^PLINK v//;s/ .*//'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@lyh970817"
maintainers:
  - "@lyh970817"
