---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bwa=0.7.17
  - bioconda::motus=3.1.0
  - bioconda::htslib=1.12
  - bioconda::samtools=1.12
  - conda-forge::numpy=1.24.2
  - conda-forge::pandas=1.5.3
  - conda-forge::python=3.9.9

