# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fgumi_simplex"
description: |
  Calls simplex consensus sequences from reads with the same unique molecular tag.
  This is a high-performance replacement for fgbio CallMolecularConsensusReads.
keywords:
  - umi
  - consensus
  - simplex
  - bam
tools:
  - "fgumi":
      description: "High-performance tools for working with UMI-tagged sequencing data."
      homepage: "https://github.com/fulcrumgenomics/fgumi"
      documentation: "https://docs.rs/fgumi"
      tool_dev_url: "https://github.com/fulcrumgenomics/fgumi"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - grouped_bam:
        type: file
        description: |
          The input SAM or BAM file, grouped by UMIs
        pattern: "*.{bam,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
  - min_reads:
      type: integer
      description: Minimum number of original reads to build each consensus read.

output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: |
            Output SAM or BAM file with simplex consensus reads.
          pattern: "*.{bam,sam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
  versions_fgumi:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fgumi:
          type: string
          description: The tool name
      - 'fgumi --version | sed "s/^fgumi //"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fgumi:
          type: string
          description: The tool name
      - 'fgumi --version | sed "s/^fgumi //"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@sppearce"
maintainers:
  - "@sppearce"
