name: hmmer_hmmalign
description: hmmalign from the HMMER suite aligns a number of sequences to an HMM
  profile
keywords:
  - alignment
  - HMMER
  - profile
  - amino acid
  - nucleotide
tools:
  - hmmer:
      description: Biosequence analysis using profile hidden Markov models
      homepage: http://hmmer.org/
      documentation: http://hmmer.org/documentation.html
      doi: "10.1371/journal.pcbi.1002195"
      licence: ["BSD-3-Clause"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: Amino acid or nucleotide gzipped compressed fasta file
        pattern: "*.{fna.gz,faa.gz,fasta.gz,fa.gz}"
        ontologies: []
  - hmm:
      type: file
      description: A gzipped HMM file
      pattern: "*.hmm.gz"
      ontologies:
        - edam: http://edamontology.org/format_3989 # GZIP format
output:
  sto:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sto.gz":
          type: file
          description: Multiple alignment in gzipped Stockholm format
          pattern: "*.sto.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_hmmer:
    - - ${task.process}:
          type: string
          description: The process name
      - hmmer:
          type: string
          description: The tool name
      - hmmalign -h | grep -o '^# HMMER [0-9.]*' | sed 's/^# HMMER //':
          type: eval
          description: The tool version

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process name
      - hmmer:
          type: string
          description: The tool name
      - hmmalign -h | grep -o '^# HMMER [0-9.]*' | sed 's/^# HMMER //':
          type: eval
          description: The tool version

authors:
  - "@erikrikarddaniel"
  - "@jfy133"
maintainers:
  - "@erikrikarddaniel"
  - "@jfy133"
  - "@vagkaratzas"
