name: idemux
description: Demultiplex paired-end FASTQ files from QuantSeq-Pool
keywords:
  - demultiplex
  - lexogen
  - fastq
tools:
  - idemux:
      description: |
        A Lexogen tool for demultiplexing and index error correcting fastq files. Works with Lexogen i7, i5 and i1 barcodes.
      homepage: https://github.com/Lexogen-Tools/idemux
      documentation: https://github.com/Lexogen-Tools/idemux
      tool_dev_url: https://github.com/Lexogen-Tools/idemux
      licence:
        - "LEXOGEN"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'NVQ', lane:1 ]
    - reads:
        type: file
        description: |
          List of input FastQ files
        pattern: "Undetermined_S*.fastq.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
    - samplesheet:
        type: file
        description: Input samplesheet
        pattern: "*.{csv}"
        ontologies:
          - edam: http://edamontology.org/format_3752 # CSV
output:
  fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'NVQ', lane:1 ]
      - "[!undetermined]*.fastq.gz":
          type: file
          description: Demultiplexed sample FASTQ files
          pattern: "*.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  undetermined:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'NVQ', lane:1 ]
      - undetermined_R?.fastq.gz:
          type: file
          description: Optional undetermined sample FASTQ files
          pattern: "Undetermined_R?.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  stats:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'NVQ', lane:1 ]
      - demultipexing_stats.tsv:
          type: file
          description: Demultiplexing Stats
          pattern: "demultipexing_stats.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions_idemux:
    - - ${task.process}:
          type: string
          description: The name of the process
      - idemux:
          type: string
          description: The name of the tool
      - idemux --version |& sed '1!d ; s/idemux //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - idemux:
          type: string
          description: The name of the tool
      - idemux --version |& sed '1!d ; s/idemux //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@jaanckae"
maintainers:
  - "@jaanckae"
