name: "pcne"
description: "Estimates plasmid copy number from assembled genome"
keywords:
  - plasmid
  - copy number
  - genomics
  - alignment
  - coverage
tools:
  - "pcne":
      description: "Estimates plasmid copy number from assembled genome."
      homepage: "https://github.com/riccabolla/PCNE"
      documentation: "https://github.com/riccabolla/PCNE"
      tool_dev_url: "https://github.com/riccabolla/PCNE"
      doi: "10.1177/11779322251410037"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - reads:
        type: file
        description: FASTQ reads (paired or single) or a pre-aligned BAM file
        pattern: "*.{fastq.gz,fq.gz,fastq,fq,bam}"
        ontologies:
          - edam: "http://edamontology.org/format_1930" # FASTQ
          - edam: "http://edamontology.org/format_2572" # BAM
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference chromosome information
          e.g. `[ id:'genome' ]`
    - chromosome:
        type: file
        description: Chromosome contigs FASTA file
        pattern: "*.{fasta,fa,fasta.gz,fa.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference plasmid information
          e.g. `[ id:'plasmids' ]`
    - plasmids:
        type: file
        description: One or more plasmid FASTA files
        pattern: "*.{fasta,fa,fasta.gz,fa.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA
output:
  results:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_results.tsv":
          type: file
          description: TSV file containing the estimated plasmid copy numbers
          pattern: "*_results.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3475"
  log:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.log":
          type: file
          description: PCNE run log file
          pattern: "*.log"
          ontologies:
            - edam: "http://edamontology.org/format_2330"
  plots:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.png":
          type: file
          description: Bar plot of plasmid copy numbers or GC vs Depth diagnostic
            plots
          pattern: "*.png"
          ontologies:
            - edam: "http://edamontology.org/format_3603"
  versions_pcne:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "pcne":
          type: string
          description: The name of the tool
      - "pcne -v | grep 'version' | tail -n 1 | sed 's/.*version //'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "pcne":
          type: string
          description: The name of the tool
      - "pcne -v | sed 's/.*version //'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@riccabolla"
maintainers:
  - "@riccabolla"
