name: "artic_aligntrim"
description: Standalone version of fieldbioinformatics aligntrim. Soft clips
  amplicon scheme primer sites in BAM/SAM files.
keywords:
  - artic
  - primer trimming
  - amplicon
  - genomics
  - sequencing
  - nanopore
  - illumina
tools:
  - "align_trim":
      description: "ARTIC align_trim: A tool for trimming amplicon sequencing primers
        from aligned reads."
      homepage: "https://github.com/artic-network/align_trim"
      documentation: "https://github.com/artic-network/align_trim/blob/master/README.md"
      tool_dev_url: "https://github.com/artic-network/align_trim"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - samfile:
        type: file
        description: BAM or SAM file containing aligned reads
        pattern: "*.{bam,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # SAM
    - scheme_bed:
        type: file
        description: BED file containing amplicon scheme primer locations
        pattern: "*.bed"
        ontologies:
          - edam: "http://edamontology.org/format_3617"
    - normalise_depth:
        type: integer
        description: Normalise the read depth to this value
  - sort_bam:
      type: boolean
      description: Optionally sort the BAM file after trimming
output:
  primertrimmed_bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.primertrimmed*.bam":
          type: file
          description: BAM file with primer sequences soft clipped
          pattern: "*.primertrimmed*.bam"
          ontologies:
            - edam: http://edamontology.org/format_2572
  align_trim_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.align_trim_report.tsv":
          type: file
          description: TSV report containing full details of primer trimming for
            each read / read pair
          pattern: "*.align_trim_report.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3750
            - edam: http://edamontology.org/format_3475
  amp_depth_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.amp_depth_report.tsv":
          type: file
          description: TSV report containing mean depth per amplicon
          pattern: "*.amp_depth_report.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3750
            - edam: http://edamontology.org/format_3475
  versions_align_trim:
    - - ${task.process}:
          type: string
          description: The name of the process
      - align_trim:
          type: string
          description: The name of the tool
      - align_trim --version | sed 's/align_trim //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - align_trim:
          type: string
          description: The name of the tool
      - align_trim --version | sed 's/align_trim //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@BioWilko"
maintainers:
  - "@BioWilko"
