name: "varnet"
description: VarNet is a deep learning based somatic variant caller that takes aligned
  reads (in BAM format) from tumor and optionally normal data, produces pileup image
  tensors from them, classifies each tensor using a convolutional neural network, and
  finally reports somatic variants in a VCF file.
keywords:
  - variant calling
  - machine learning
  - neural network
tools:
  - "varnet":
      description: "A deep learning based somatic variant caller"
      homepage: "https://github.com/skandlab/varnet"
      documentation: "https://github.com/skandlab/varnet"
      tool_dev_url: "https://github.com/skandlab/varnet"
      doi: "10.1038/s41467-022-30584-2"
      licence:
        - "Polyform Non-Commercial"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input_normal:
        type: file
        description: BAM/CRAM file
        pattern: "*.bam/cram"
        ontologies: []
    - index_normal:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.bai/crai"
        ontologies: []
    - input_tumor:
        type: file
        description: BAM/CRAM file
        pattern: "*.bam/cram"
        ontologies: []
    - index_tumor:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.bai/crai"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - intervals:
        type: file
        description: file containing intervals
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fai"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}.vcf.gz:
          type: file
          description: Compressed VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format

  versions_varnet:
    - - ${task.process}:
          type: string
          description: The name of the process
      - varnet:
          type: string
          description: The name of the tool
      - "1.5.0":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - varnet:
          type: string
          description: The name of the tool
      - "1.5.0":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@vaxyzek"
maintainers:
  - "@vaxyzek"
