name: "hmmer_hmmrank"
description: R script that scores output from multiple runs of hmmer/hmmsearch
keywords:
  - hmmer
  - hmmsearch
  - rank
tools:
  - "hmmer":
      description: "Biosequence analysis using profile hidden Markov models"
      homepage: http://hmmer.org/
      documentation: http://hmmer.org/documentation.html
      tool_dev_url: https://github.com/EddyRivasLab/hmmer
      doi: "10.1371/journal.pcbi.1002195"
      licence:
        - "BSD"
      identifier: ""
  - "R":
      description: "A Language and Environment for Statistical Computing"
      homepage: https://www.r-project.org/
      documentation: https://www.r-project.org/
      licence:
        - "GPL v2"
      identifier: ""
  - "Tidyverse":
      description: "Tidyverse: R packages for data science"
      homepage: https://www.tidyverse.org/
      documentation: https://www.tidyverse.org/
      tool_dev_url: https://github.com/tidyverse
      doi: "10.21105/joss.01686"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - tblouts:
        type: file
        description: table outputs from hmmsearch
        pattern: "*.tsv.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
output:
  hmmrank:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.hmmrank.tsv.gz":
          type: file
          description: TSV file with ranked hmmer results
          pattern: "*.hmmrank.tsv.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_r:
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-base:
          type: string
          description: The name of the tool
      - R --version | sed '1!d; s/.*version //; s/ .*//':
          type: eval
          description: The expression to obtain the version of the tool
  versions_r_tidyverse:
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-tidyverse:
          type: string
          description: The name of the tool
      - Rscript -e "cat(as.character(packageVersion('tidyverse')))":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-base:
          type: string
          description: The name of the tool
      - R --version | sed '1!d; s/.*version //; s/ .*//':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-tidyverse:
          type: string
          description: The name of the tool
      - Rscript -e "cat(as.character(packageVersion('tidyverse')))":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@erikrikarddaniel"
maintainers:
  - "@erikrikarddaniel"
