name: idr
description: |
  Measures reproducibility of ChIP-seq, ATAC-seq peaks using IDR (Irreproducible
  Discovery Rate)
keywords:
  - IDR
  - peaks
  - ChIP-seq
  - ATAC-seq
tools:
  - idr:
      description: |
        The IDR (Irreproducible Discovery Rate) framework is a uniﬁed approach
        to measure the reproducibility of ﬁndings identiﬁed from replicate
        experiments and provide highly stable thresholds based on reproducibility.
      tool_dev_url: https://github.com/kundajelab/idr
      licence:
        - "GPL v2"
      identifier: biotools:idr
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test']
    - peaks:
        type: list
        description: BED, narrowPeak or broadPeak files of replicates
        pattern: "*"
    - peak_type:
        type: string
        description: Type of peak file
        pattern: "{narrowPeak,broadPeak,bed}"
output:
  idr:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*idrValues.txt":
          type: file
          description: Text file containing IDR values
          pattern: "*.{txt}"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*log.txt":
          type: file
          description: Log file
          pattern: "*.{txt}"
          ontologies: []
  png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*.png":
          type: file
          description: Plot generated by idr
          pattern: "*{.png}"
          ontologies: []
  versions_idr:
    - - ${task.process}:
          type: string
          description: The name of the process
      - idr:
          type: string
          description: The name of the tool
      - idr --version |& sed '1!d;s/^.*IDR //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version |& sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - idr:
          type: string
          description: The name of the tool
      - idr --version |& sed '1!d;s/^.*IDR //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version |& sed 's/Python //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@drpatelh"
  - "@joseespinosa"
maintainers:
  - "@drpatelh"
  - "@joseespinosa"
