# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "suppa_generateevents"
description: "Generates alternative splicing events from a GTF file using SUPPA."
keywords:
  - suppa
  - alternative splicing
  - genomics
tools:
  - "suppa":
      description: "Fast, accurate, and uncertainty-aware differential splicing analysis across multiple conditions."
      homepage: "https://github.com/comprna/SUPPA"
      documentation: "https://github.com/comprna/SUPPA"
      tool_dev_url: "https://github.com/comprna/SUPPA"
      doi: "10.1186/s13059-018-1417-1"
      licence: ["MIT"]
      identifier: biotools:suppa

input:
  - gtf:
      type: file
      description: GTF file
      pattern: "*.gtf"
      ontologies:
        - edam: http://edamontology.org/format_3475
  - format:
      type: string
      description: Format of the events to be generated. Options are "ioe" or "ioi".
  - pool_genes:
      type: boolean
      description: Whether to pool genes or not. If true, events will be generated for all genes together.
  - event_type:
      type: string
      description: Type of alternative splicing events to be generated. Options are "SE", "A5", "A3", "RI", "MX", "AF", "AL".
  - boundary:
      type: integer
      description: Boundary for event generation
  - threshold:
      type: float
      description: Threshold for event generation
  - exon_length:
      type: integer
      description: Minimum exon length for event generation
output:
  events:
    - "events*.*":
        type: file
        description: Alternative splicing events
        pattern: "events*.*"
        ontologies: []
  versions_suppa:
    - - ${task.process}:
          type: string
          description: The name of the process
      - suppa:
          type: string
          description: The name of the tool
      - "suppa.py -v | sed '1!d;s/.* //'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - suppa:
          type: string
          description: The name of the tool
      - suppa.py -v | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@lathikaa"
maintainers:
  - "@piplus2"
