name: bismark_genomepreparation
description: |
  Converts a specified reference genome into two different bisulfite
  converted versions and indexes them for alignments.
keywords:
  - bismark
  - 3-letter genome
  - index
  - methylation
  - 5mC
  - methylseq
  - bisulphite
  - bisulfite
  - fasta
tools:
  - bismark:
      description: |
        Bismark is a tool to map bisulfite treated sequencing reads
        and perform methylation calling in a quick and easy-to-use fashion.
      homepage: https://github.com/FelixKrueger/Bismark
      documentation: https://github.com/FelixKrueger/Bismark/tree/master/Docs
      doi: 10.1093/bioinformatics/btr167
      licence:
        - "GPL-3.0-or-later"
      identifier: biotools:bismark
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies: []
output:
  index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - BismarkIndex:
          type: directory
          description: Bismark genome index directory
          pattern: "BismarkIndex"
  versions_bismark:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bismark:
          type: string
          description: The name of the tool
      - "bismark --version 2>&1 | sed -n 's/^.*Bismark Version: v//p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bismark:
          type: string
          description: The name of the tool
      - "bismark --version 2>&1 | sed -n 's/^.*Bismark Version: v//p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@phue"
maintainers:
  - "@phue"
  - "@sateeshperi"
