# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "parsnp"
description: "Parsnp is a command-line-tool for efficient microbial core genome alignment and SNP detection."
keywords:
  - alignment
  - bacteria
  - phylogeny
  - microbial genomics
  - core genome
  - SNP

tools:
  - "parsnp":
      description: "Parsnp is a command-line-tool for efficient microbial core genome alignment and SNP detection."
      homepage: "https://harvest.readthedocs.io/en/latest/content/parsnp/tutorial.html"
      documentation: "https://harvest.readthedocs.io/en/latest/content/parsnp/tutorial.html"
      tool_dev_url: "https://github.com/marbl/parsnp"
      doi: "10.1093/bioinformatics/btae311"
      licence: ["custom; see https://raw.githubusercontent.com/marbl/parsnp/master/LICENSE"]
      identifier: biotools:parsnp

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - genomes:
        type: directory
        description: Directory containing genome assemblies in FASTA format to be aligned
  - reference:
      type: file
      description: Reference genome in FASTA format
      pattern: "*.{fasta,fa,fna}"
      ontologies:
        - edam: "http://edamontology.org/format_1929" # FASTA

output:
  xmfa:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.xmfa":
          type: file
          description: Core-genome multiple sequence alignment in XMFA format
          pattern: "*.xmfa"
  ggr:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.ggr":
          type: file
          description: Compressed binary representation of the alignment generated by the Harvest toolkit, used for visualization with Gingr
          pattern: "*.ggr"
  snps_mblocks:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.snps.mblocks":
          type: file
          description: Core-SNP signature of each sequence in FASTA format, used to generate the phylogeny. Absent when no SNPs are detected.
          pattern: "*.snps.mblocks"
          ontologies:
            - edam: "http://edamontology.org/format_1929" # FASTA
  tree:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tree":
          type: file
          description: Resulting phylogeny in Newick format
          pattern: "*.tree"
          ontologies:
            - edam: "http://edamontology.org/format_1910" # Newick
  partition:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "partition":
          type: directory
          description: Output directory from partition mode containing results of each partitioned run. Only present when --partition is specified.
          pattern: "partition"
  versions_parsnp:
    - - ${task.process}:
          type: string
          description: The name of the process
      - parsnp:
          type: string
          description: The name of the tool
      - "parsnp --version 2>/dev/null | tail -n 1 | sed 's/parsnp //'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process
      - parsnp:
          type: string
          description: The tool name
      - parsnp --version 2>/dev/null | tail -n 1 | sed 's/parsnp //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@emmcauley"
maintainers:
  - "@emmcauley"
