# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bwamem3_index"
description: Create bwa-mem3 index for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - "bwamem3":
      description: "Short-read aligner derived from bwa-mem2 with correctness fixes,
        performance improvements, and methylation-aware alignment."
      homepage: "https://github.com/fg-labs/bwa-mem3"
      documentation: "https://github.com/fg-labs/bwa-mem3"
      tool_dev_url: "https://github.com/fg-labs/bwa-mem3"
      licence: ["MIT AND Apache-2.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies:
          - edam: "http://edamontology.org/data_2044"
          - edam: "http://edamontology.org/format_1929"
output:
  index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - bwamem3:
          type: directory
          description: bwa-mem3 genome index files
          pattern: "*.{0123,amb,ann,bwt.2bit.64,pac}"
          ontologies:
            - edam: "http://edamontology.org/data_3210"
  versions_bwamem3:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwamem3:
          type: string
          description: The name of the tool
      - bwa-mem3 version 2>/dev/null | head -n1 | grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwamem3:
          type: string
          description: The name of the tool
      - bwa-mem3 version 2>/dev/null | head -n1 | grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nh13"
maintainers:
  - "@nh13"
