# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_variant_calling_sort_freebayes_bcftools"
description: Call variants using freebayes, then sort and index
keywords:
  - variant
  - sort
  - index
  - bam
  - cram
  - vcf
components:
  - freebayes
  - bcftools/sort
input:
  - ch_input:
      type: file
      description: |
        Alignments to call variants from, where `input1` is a BAM/CRAM/SAM file with its
        index `index1`, `input2` is an optional second BAM/CRAM/SAM file with its index
        `index2` used to run variant calling with a pair (normal vs tumour), and `bed` is
        an optional BED file limiting the analysis to the targets listed in it.

        Structure: [ val(meta), path(input1), path(index1), path(input2), path(index2), path(bed) ]
  - ch_fasta_fai:
      type: file
      description: |
        Reference fasta file and its index.

        Structure: [ val(meta2), path(fasta), path(fai) ]
  - ch_samples:
      type: file
      description: |
        Optional - Limit analysis to samples listed (one per line) in the file.

        Structure: [ val(meta3), path(samples) ]
      pattern: "*.txt"
  - ch_populations:
      type: file
      description: |
        Optional - Each line of the file should list a sample and a population which it is part of.

        Structure: [ val(meta4), path(populations) ]
      pattern: "*.txt"
  - ch_cnv:
      type: file
      description: |
        Optional - A copy number map BED file, which has either a sample-level ploidy:
        sample_name copy_number
        or a region-specific format:
        seq_name start end sample_name copy_number

        Structure: [ val(meta5), path(cnv) ]
      pattern: "*.bed"
output:
  - vcf_index:
      type: file
      description: |
        Sorted VCF file with its index.

        Structure: [ val(meta), path(vcf), path(index) ]
authors:
  - "@priyanka-surana"
  - "@FriederikeHanssen"
  - "@ramprasadn"
maintainers:
  - "@priyanka-surana"
  - "@FriederikeHanssen"
  - "@ramprasadn"
