name: "sylphtax_merge"
description: Merge multiple taxonomic profiles from sylphtaxt/taxprof into a tsv table
keywords:
  - sylph
  - metagenomics
  - merge
tools:
  - sylphtax:
      description: Integrating taxonomic information into the sylph metagenome profiler.
      homepage: https://github.com/bluenote-1577/sylph-tax?tab=readme-ov-file
      documentation: https://sylph-docs.github.io/sylph-tax/
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - sylphtax_reports:
        type: file
        description: Output taxonomic profile from sylph-tax taxprof command.
        pattern: "*.{sylphmpa}"
        ontologies:
          - edam: http://edamontology.org/format_3475 # TSV
  - data_type:
      type: string
      description: Can be ANI, relative abundance, or sequence abundance.
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tsv":
          type: file
          description: Output profile with the merged taxonomic profiles in tsv format.
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions_sylphtax:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sylph-tax:
          type: string
          description: The name of the tool
      - sylph-tax --version 2>&1 | tail -1:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sylph-tax:
          type: string
          description: The name of the tool
      - sylph-tax --version 2>&1 | tail -1:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@sofstam"
maintainers:
  - "@sofstam"
