name: "universc"
description: Module to run UniverSC an open-source pipeline to demultiplex and process
  single-cell RNA-Seq data
keywords:
  - demultiplex
  - align
  - single-cell
  - scRNA-Seq
  - count
  - umi
tools:
  - "universc":
      description: "UniverSC: a flexible cross-platform single-cell data processing
        pipeline"
      homepage: "https://hub.docker.com/r/tomkellygenetics/universc"
      documentation: "https://raw.githubusercontent.com/minoda-lab/universc/master/man/launch_universc.sh"
      tool_dev_url: "https://github.com/minoda-lab/universc"
      doi: "10.1101/2021.01.19.427209"
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:universc
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: FASTQ or FASTQ.GZ file, list of 2 files for paired-end data
        pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
        ontologies:
          - edam: http://edamontology.org/format_1930 # FASTQ
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'Hg38' ]
    - reference:
        type: file
        description: Reference genome file
        ontologies: []
  - technology:
      type: string
      description: Technology to pass to universc `--technology argument`
output:
  outs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/outs/*:
          type: file
          description: Files containing the outputs of Cell Ranger
          pattern: "${prefix}/outs/*"
          ontologies: []
  versions_cellranger:
    - - ${task.process}:
          type: string
          description: The name of the process
      - cellranger:
          type: string
          description: The name of the tool
      - 'cellranger count --version 2>&1 | head -n 2 | tail -n 1 | sed "s/^.* //g" | sed "s/(//g" | sed "s/)//g"':
          type: eval
          description: The expression to obtain the version of the tool
  versions_universc:
    - - ${task.process}:
          type: string
          description: The name of the process
      - universc:
          type: string
          description: The name of the tool
      - 'bash /universc/launch_universc.sh --version | grep version | grep universc | sed "s/^.* //g"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - cellranger:
          type: string
          description: The name of the tool
      - 'cellranger count --version 2>&1 | head -n 2 | tail -n 1 | sed "s/^.* //g" | sed "s/(//g" | sed "s/)//g"':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - universc:
          type: string
          description: The name of the tool
      - 'bash /universc/launch_universc.sh --version | grep version | grep universc | sed "s/^.* //g"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@kbattenb"
  - "@tomkellygenetics"
maintainers:
  - "@kbattenb"
  - "@tomkellygenetics"
