name: "proseg"
description: "Proseg (probabilistic segmentation) is a cell segmentation method for
  in situ spatial transcriptomics."
keywords:
  - segmentation
  - spatial
  - transcriptomics
tools:
  - "proseg":
      description: "Proseg (probabilistic segmentation) is a cell segmentation method
        for in situ spatial transcriptomics."
      homepage: "https://github.com/dcjones/proseg"
      documentation: "https://github.com/dcjones/proseg"
      tool_dev_url: "https://github.com/dcjones/proseg"
      doi: "10.1038/s41592-025-02697-0"
      licence:
        - "GPLv3"
      identifier: ""
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information
    - transcripts:
        type: file
        description: Transcript ids, genes, revised positions, assignment
          probability, etc.
        pattern: "*transcript-metadata.{csv.gz,csv,parquet}"
        ontologies:
          - edam: http://edamontology.org/format_3752
  - mode:
      type: string
      description: Proseg preset mode
      enum:
        - "xenium"
        - "merfish"
        - "cosmx"
  - - transcript_metadata_fmt:
        type: string
        description: Format of the transcript metadata file
        enum:
          - "csv"
          - "csv.gz"
          - "parquet"
    - cell_metadata_fmt:
        type: file
        description: Format of the cell metadata file
        enum:
          - "csv"
          - "csv.gz"
          - "parquet"
        ontologies: []
    - expected_counts_fmt:
        type: file
        description: Format of the expected counts file
        enum:
          - "csv"
          - "csv.gz"
          - "parquet"
        ontologies: []
output:
  zarr:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}.zarr:
          type: file
          description: "Path to the output spatialdata Zarr file."
          pattern: "*.zarr"
          ontologies:
            - edam: http://edamontology.org/format_3470
  transcript_metadata:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_transcript-metadata.{csv,csv.gz,parquet}:
          type: file
          description: Transcript ids, genes, revised positions, assignment
            probability, etc.
          pattern: "*transcript-metadata.{csv.gz,csv,parquet}"
          ontologies:
            - edam: http://edamontology.org/format_3752
  cell_polygons:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_cell-polygons.geojson.gz:
          type: file
          description: "Path to the cell polygons file."
          pattern: "*cell-polygons.geojson.gz"
          ontologies:
            - edam: http://edamontology.org/format_3464
            - edam: http://edamontology.org/format_3989
  cell_metadata:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_cell-metadata.{csv,csv.gz,parquet}:
          type: file
          description: "Path to the cell metadata file."
          pattern: "*cell-metadata.{csv.gz,csv,parquet}"
          ontologies:
            - edam: http://edamontology.org/format_3752
  cell_polygons_layers:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_cell-polygons-layers.geojson.gz:
          type: file
          description: "Path to the cell polygons layers file."
          pattern: "*cell-polygons-layers.geojson.gz"
          ontologies:
            - edam: http://edamontology.org/format_3464
            - edam: http://edamontology.org/format_3989
  expected_counts:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_expected-counts.{csv,csv.gz,parquet}:
          type: file
          description: "Path to the expected counts file."
          pattern: "*expected-counts.{csv.gz,csv,parquet}"
          ontologies:
            - edam: http://edamontology.org/format_3752
  union_cell_polygons:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}_cell-polygons-union.geojson.gz:
          type: file
          description: "Path to the union cell polygons file."
          pattern: "*cell-polygons-union.geojson.gz"
          ontologies:
            - edam: http://edamontology.org/format_3464
            - edam: http://edamontology.org/format_3989
  versions_proseg:
    - - ${task.process}:
          type: string
          description: The name of the process
      - proseg:
          type: string
          description: The name of the tool
      - proseg --version | sed 's/proseg //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - proseg:
          type: string
          description: The name of the tool
      - proseg --version | sed 's/proseg //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@derrik-gratz"
  - "@khersameesh24"
maintainers:
  - "@derrik-gratz"
  - "@khersameesh24"
