channels:
  - conda-forge
  - bioconda
dependencies:
- bioconda::bioconductor-anndatar=1.0.2
- bioconda::bioconductor-rhdf5=2.54.1
- conda-forge::r-leidenbase=0.1.36
- conda-forge::r-seurat=5.4.0
- conda-forge::r-soupx=1.6.2
