name: rami2d-env
channels:
- conda-forge
- bioconda
dependencies:
- pip=25.3
- python=3.11.13
- tifffile=2025.6.11
- conda-forge::ome-types=0.6.1
- scikit-image=0.25.2
- pandas=2.2.2
- conda-forge::matplotlib=3.10.8
- conda-forge::imagecodecs=2026.3.6
- lxml=6.0.2
- pip:
  - itk-elastix==0.23.0
  - openslide-python==1.4.2
  - openslide-bin==4.0.0.8
  - rami2d==1.0.0