channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fusion-report=4.1.1
  - conda-forge::beautifulsoup4=4.14.3
  - conda-forge::click=8.4.0
  - conda-forge::colorlog=6.10.1
  - conda-forge::jinja2=3.1.6
  - conda-forge::markupsafe=3.0.3
  - conda-forge::numpy=2.4.6
  - conda-forge::openpyxl=3.1.5
  - conda-forge::pandas=3.0.3
  - conda-forge::pyyaml=6.0.3
  - conda-forge::requests=2.34.2
  - conda-forge::tabulate=0.10.0
  - conda-forge::tqdm=4.67.3
  - conda-forge::xlrd=2.0.2
