---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.4.3
  - conda-forge::r-data.table=1.16.4
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-zoo=1.8_12
