name: "rami2d_register"
description: offers 3 pre-defined registration schemes 1) Rigid, 2) Rigid+Affine 3) Rigid+Affine+Bsplines, each of them providing more geometrical adaptability and thus more control in the final outcome.
keywords:
  - registration
  - imaging
  - multiplex
  - spatial
tools:
  - "rami2d":
      description: "Robust Alignment of Multichannel Images in 2D"
      homepage: "https://pypi.org/project/rami2d/"
      documentation: "https://github.com/VictorDidier/RAMI2D"
      tool_dev_url: "https://github.com/VictorDidier/RAMI2D"
      doi: ""
      licence: "['BSD 3-Clause']"
      identifier: "rami2d"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing fixed image sample information
          e.g. `[ id:'sample1' ]`
    - fixed_img:
        type: file
        description: Absolute path of the image stack containing the fixed image
        pattern: "*.{tif,tiff,ome.tif,ome.tiff,svs,avs,vms,dcm,vmus,ndpi,scn,mrxs,svslide,bif,czi}"
    - moving_img:
        type: file
        description: Absolute path of the image stack containing the moving image
        pattern: "*.{tif,tiff,ome.tif,ome.tiff,svs,avs,vms,dcm,vmus,ndpi,scn,mrxs,svslide,bif,czi}"
  - - ifix:
        type: integer
        description: O-based Index of the channel to be used for the registration in the fixed image stack
  - - imov:
        type: integer
        description: O-based Index of the channel to be used for the registration in the moving image stack
  - - mpp_fix:
        type: float
        description: Pixel size of the fixed image in micrometers
  - - mpp_mov:
        type: float
        description: Pixel size of the moving image in micrometers
  - - mpp_reg:
        type: float
        description: Image resolution in micrometers to be used for applying the registration scheme
output:
  - registered_image:
      - - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'sample1' ]`
        - "*/*.ome.tif":
            type: file
            description: Registered output image in pyramidal OME TIFF format
            pattern: "*.ome.tif"
  - csv:
      - - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'sample1' ]`
        - "*/*.csv":
            type: file
            description: Output CSV file containing registration metrics
            pattern: "*.csv"
  - qc_dir:
      - - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'sample1' ]`
        - "*/qc":
            type: directory
            description: Directory containing QC outputs including refchns keypoints and fullres transformations
            pattern: "qc"
  - versions_rami2d:
      - - ${task.process}:
            type: string
            description: Name of the task process
        - rami2d:
            type: string
            description: Name of the tool
        - 'rami2d-register -v | sed "s/rami2d-register //"':
            type: eval
            description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: Name of the task process
      - rami2d:
          type: string
          description: Name of the tool
      - 'rami2d-register -v | sed "s/rami2d-register //"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"