---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.12.4
  - readimc=0.7.0
  - ome-types=0.5.1.post1
  - tifffile=2023.2.28
  - scipy=1.13.1
  - pip=25.3
  - pip:
      - imc2mc==0.0.3
