name: "odgi_view"
description: Project a graph into other formats.
keywords:
  - variation graph
  - pangenome graph
  - gfa
  - graph formats
tools:
  - "odgi":
      description: "An optimized dynamic genome/graph implementation"
      homepage: "https://github.com/pangenome/odgi"
      documentation: "https://odgi.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/pangenome/odgi"
      doi: "10.1093/bioinformatics/btac308"
      licence:
        - "MIT"
      identifier: biotools:odgi
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - graph:
        type: file
        description: Pangenome graph in GFA v1.0 format or in ODGI binary format
        pattern: "*.{gfa,og}"
        ontologies:
          - edam: http://edamontology.org/format_3975
output:
  gfa:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gfa":
          type: file
          description: File containing a pangenome graph in GFA v1.0 format.
          pattern: "*.{gfa}"
          ontologies:
            - edam: http://edamontology.org/format_3975
  versions_odgi:
    - - ${task.process}:
          type: string
          description: The name of the process
      - odgi:
          type: string
          description: The name of the tool
      - odgi version | sed 's/^v//; s|-.*||':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - odgi:
          type: string
          description: The name of the tool
      - odgi version | sed 's/^v//; s|-.*||':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@subwaystation"
maintainers:
  - "@subwaystation"
