---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - genomedk
dependencies:
  - conda-forge::r-base=4.3.1
  - genomedk::ldak6=6.1
