---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-updhmm=1.6.0
  - bioconda::bioconductor-variantannotation=1.56.0
  - conda-forge::r-base=4.5.0
