name: "ngsbits_bedannotategc"
description: Annotates GC content fraction to regions in a BED file.
keywords:
  - gc
  - bed
  - regions
tools:
  - "ngsbits":
      description: "Short-read sequencing tools"
      homepage: "https://github.com/imgag/ngs-bits"
      documentation: "https://github.com/imgag/ngs-bits"
      tool_dev_url: "https://github.com/imgag/ngs-bits"
      licence:
        - "MIT"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bed:
        type: file
        description: Input BED file containing regions to annotate
        pattern: "*.bed"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference fasta information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: The reference FASTA to use
        pattern: "*.{fasta,fa,fna}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference fasta information
          e.g. `[ id:'sample1', single_end:false ]`
    - fai:
        type: file
        description: The index file from the reference FASTA
        pattern: "*.fai"

        ontologies: []
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bed":
          type: file
          description: Annotated BED file with GC content fraction
          pattern: "*.bed"
          ontologies: []
  versions_ngsbits:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - BedAnnotateGC --version 2>&1 | grep BedAnnotateGC | sed 's/BedAnnotateGC //':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - BedAnnotateGC --version 2>&1 | grep BedAnnotateGC | sed 's/BedAnnotateGC //':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/ngs-bits:2026_06--ded3d87a5c0a98ee
      build_id: bd-ded3d87a5c0a98ee_1
      scan_id: sc-f7a23e68d81b01b0_1
    linux/amd64:
      name: community.wave.seqera.io/library/ngs-bits:2026_06--10de2f01af4c9c32
      build_id: bd-10de2f01af4c9c32_1
      scan_id: sc-ed9d8aa51d32d8c4_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/ngs-bits:2026_06--68b7658e81716a8e
      build_id: bd-68b7658e81716a8e_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e8/e833a9ec91195ab6632d4f69260e788bafd42a05fbad4acd4d064e491b9091f6/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/ngs-bits:2026_06--eefe177929fb17d1
      build_id: bd-eefe177929fb17d1_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/db/db759890fb18613dd6178305e20a588bda85a12c3d06f885899aca2f54725985/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/ngsbits/bedannotategc/.conda-lock/linux_amd64-bd-10de2f01af4c9c32_1.txt
    linux/arm64:
      lock_file: modules/nf-core/ngsbits/bedannotategc/.conda-lock/linux_arm64-bd-ded3d87a5c0a98ee_1.txt
