# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: fastq_download_prefetch_fasterqdump_sratools
description: Download FASTQ sequencing reads from the NCBI's Sequence Read Archive (SRA).
keywords:
  - SRA
  - NCBI
  - sequencing
  - fastq
  - prefetch
  - fasterq-dump
components:
  - custom/sratoolsncbisettings
  - sratools/prefetch
  - sratools/fasterqdump
input:
  - ch_sra_ids:
      type: string
      description: |
        SRA run identifier.

        Structure: [ val(meta), val(id) ]
  - ch_dbgap_key:
      type: file
      description: |
        Path to a JWT cart file used to access protected dbGAP data on SRA using the sra-toolkit

        Structure: [ path(dbgap_key) ]
      pattern: "*.cart"
output:
  - reads:
      type: file
      description: |
        Extracted FASTQ file or files if the sequencing reads are paired-end.

        Structure: [ val(meta), [ path(reads) ] ]
      pattern: "*.fastq.gz"
authors:
  - "@Midnighter"
  - "@drpatelh"
maintainers:
  - "@Midnighter"
  - "@drpatelh"
