name: graphmap2_index
description: A versatile pairwise aligner for genomic and spliced nucleotide
  sequences
keywords:
  - index
  - fasta
  - reference
tools:
  - graphmap2:
      description: |
        A versatile pairwise aligner for genomic and spliced nucleotide sequences.
      homepage: https://github.com/lbcb-sci/graphmap2
      documentation: https://github.com/lbcb-sci/graphmap2#graphmap2---a-highly-sensitive-and-accurate-mapper-for-long-error-prone-reads
      licence:
        - "MIT"
      identifier: biotools:Graphmap2
input:
  - fasta:
      type: file
      description: |
        Reference database in FASTA format.
      ontologies: []
output:
  index:
    - "*.gmidx":
        type: file
        description: Index file in gmidx format
        pattern: "*.gmidx"
        ontologies: []
  versions_graphmap2:
    - - ${task.process}:
          type: string
          description: The name of the process
      - graphmap2:
          type: string
          description: The name of the tool
      - "graphmap2 2>&1 | sed -n 's/Version: v//p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - graphmap2:
          type: string
          description: The name of the tool
      - "graphmap2 2>&1 | sed -n 's/Version: v//p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@yuukiiwa"
  - "@drpatelh"
maintainers:
  - "@yuukiiwa"
  - "@drpatelh"
