# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: fastq_create_umi_consensus_fgbio
description: |
  This workflow uses the suite FGBIO to identify and remove UMI tags from FASTQ reads
  convert them to unmapped BAM file, map them to the reference genome,
  and finally use the mapped information to group UMIs and generate consensus reads in each group
keywords:
  - fgbio
  - umi
  - samblaster
  - samtools
  - bwa
components:
  - bwa/index
  - bwa/mem
  - bwamem2/mem
  - bwamem2/index
  - fgbio/fastqtobam
  - fgbio/groupreadsbyumi
  - fgbio/callmolecularconsensusreads
  - fgbio/callduplexconsensusreads
  - fgbio/filterconsensusreads
  - samblaster
  - samtools/bam2fq
  - samtools/sort
  - samtools/index
  - samtools/fastq
  - fgbio/zipperbams
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - reads:
      type: list
      description: list umi-tagged reads
      pattern: "[ *.{fastq.gz/fq.gz} ]"
  - fasta_fai_dict:
      type: file
      description: The reference fasta file, index and dictionary
      pattern: "*.{fa,fasta,fna,fai,dict}"
  - bwa_index:
      type: file
      description: The reference genome bwa index files
      pattern: "*.{fa,fasta,fna,amb,ann,bwt,pac,sa}"
  - groupreadsbyumi_strategy:
      type: string
      description: Defines the UMI assignment strategy.
      Required argument: defines the UMI assignment strategy.
      enum:
        - Identity
        - Edit
        - Adjacency
        - Paired
  - aligner:
      type: string
      description: The aligner to use for mapping the reads to the reference genome. Options are bwa-mem and bwamem2.
      enum:
        - bwa-mem
        - bwamem2
  - duplex:
      type: boolean
      description: Whether the library contains duplex UMIs.
  - min_reads:
      type: integer
      description: One integer (for non-duplex) or a string of up-to three space-separated numbers for duplex sequencing
  - min_baseq:
      type: integer
      description: Minimum base quality for bases to be considered in consensus calling.
  - max_base_error_rate:
      type: integer
      description: Maximum base error rate for consensus building
output:
  - ubam:
      type: file
      description: unmapped bam file
      pattern: "*.bam"
  - groupbam:
      type: file
      description: mapped bam file, where reads are grouped by UMI tag
      pattern: "*.bam"
  - consensusbam:
      type: file
      description: |
        mapped bam file, where reads are created as consensus of those
        belonging to the same UMI group
      pattern: "*.bam"
  - mappedconsensusbam:
      type: file
      description: |
        mapped bam file, where reads are created as consensus of those
        belonging to the same UMI group and filtered for minimum base quality and maximum error rate
      pattern: "*.bam"
authors:
  - "@lescai"
maintainers:
  - "@lescai"
