name: "ngsbits_updhunter"
description: UPD detection from trio variant data.
keywords:
  - upd
  - vcf
  - genomics
tools:
  - "ngsbits":
      description: "Short-read sequencing tools"
      homepage: "https://github.com/imgag/ngs-bits"
      documentation: "https://github.com/imgag/ngs-bits"
      tool_dev_url: "https://github.com/imgag/ngs-bits"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - vcf:
        type: file
        description: vcf file
        pattern: "*.vcf{,.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016" # VCF
    - bed:
        type: file
        description: bed file with regions to exclude
        pattern: "*.bed"
        ontologies:
          - edam: "http://edamontology.org/format_3003" # BED

output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: TSV file containing the detected UPDs
          pattern: "*.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3475" # TSV
  igv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.igv":
          type: file
          description: IGV file containing informative variants
          pattern: "*.igv"
          ontologies: []
  versions_ngsbits:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - UpdHunter --version 2>&1 | sed 's/UpdHunter //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - UpdHunter --version 2>&1 | sed 's/UpdHunter //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
