# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "goatools_findenrichment"
description: Find enriched GO terms in a list of genes
keywords:
  - goatools
  - enrichment
  - ontology
  - geneontology
  - go
  - genomics
tools:
  - "goatools":
      description: "Python scripts to find enrichment of GO terms"
      homepage: "https://github.com/tanghaibao/goatools"
      documentation: "https://github.com/tanghaibao/goatools/blob/main/README.md"
      tool_dev_url: "https://github.com/tanghaibao/goatools"
      doi: "10.1038/s41598-018-28948-z"
      licence: ["BSD-2-clause"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - study_list:
        type: file
        description: Plain text file with one study gene identifier per line
        pattern: "*.{txt,tsv,csv}"
        ontologies:
          - edam: "http://edamontology.org/format_2330" # Textual format
    - population_list:
        type: file
        description: Plain text file with one background population gene identifier per line
        pattern: "*.{txt,tsv,csv}"
        ontologies:
          - edam: "http://edamontology.org/format_2330" # Textual format
    - annotation:
        type: file
        description: Gene-to-GO association file used by GOATOOLS
        pattern: "*"
        # no meaningful ontology found for this entry
  - obo:
      type: file
      description: Gene Ontology OBO file
      pattern: "*.obo"
      ontologies:
        - edam: "http://edamontology.org/format_2549" # OBO
  - goslim:
      type: file
      description: GO slim mapping file used for slim-specific enrichment summaries
      pattern: "*.obo"
      ontologies:
        - edam: "http://edamontology.org/format_2549" # OBO

output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: GO enrichment analysis table generated by GOATOOLS find_enrichment
          pattern: "*.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3475" # TSV
  versions_goatools:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "goatools":
          type: string
          description: The name of the tool
      - "goatools --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - goatools:
          type: string
          description: The name of the tool
      - goatools --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@itrujnara"
maintainers:
  - "@itrujnara"
