name: "cnvkit_fix"
description: Combine the uncorrected target and antitarget coverage tables (.cnn) and correct for biases in regional coverage and GC content, according to the given reference.
keywords:
  - cnvkit
  - fix
  - cnn
  - GC content
  - bias
  - RepeatMasker
  - genomics
tools:
  - "cnvkit":
      description: "Copy number variant detection from high-throughput sequencing."
      homepage: "https://cnvkit.readthedocs.io/en/stable"
      documentation: "https://cnvkit.readthedocs.io/en/stable"
      tool_dev_url: "https://github.com/etal/cnvkit"
      doi: "10.1371/journal.pcbi.1004873"
      licence: ["Apache-2.0"]
      identifier: biotools:cnvkit

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - targetcoverage:
        type: file
        description: target coverage table. Output of the cnvkit coverage command.
        pattern: "*.{targetcoverage.cnn}"
        ontologies: []
    - antitargetcoverage:
        type: file
        description: antitarget coverage table. Output of the cnvkit coverage command.
        pattern: "*.{antitargetcoverage.cnn}"
        ontologies: []
    - reference:
        type: file
        description: copy-number reference.
        pattern: "*{.cnn}"
        ontologies: []
output:
  copy_number_ratio:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.cnr":
          type: file
          description: table of bias corrected copy number ratios.
          pattern: "*.{cnr}"
          ontologies: []
  versions_cnvkit:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "cnvkit":
          type: string
          description: The name of the tool
      - cnvkit.py version | sed -e "s/cnvkit v//g":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - cnvkit:
          type: string
          description: The name of the tool
      - cnvkit.py version | sed -e "s/cnvkit v//g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@aadecock"
maintainers:
  - "@aadecock"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/cnvkit:0.9.14--288e98d6210b7304
      build_id: bd-288e98d6210b7304_1
      scan_id: sc-443ec212095df1dc_1
    linux/arm64:
      name: community.wave.seqera.io/library/cnvkit:0.9.14--2b15b9d82750b6bc
      build_id: bd-2b15b9d82750b6bc_1
      scan_id: sc-6428381e648fe45a_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/cnvkit:0.9.14--5c558b3f35d90f28
      build_id: bd-5c558b3f35d90f28_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8e/8e36d8f28c489f4fe5a8927be4a21c3fb35aa8305548cff93edb4b51a51e4026/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/cnvkit:0.9.14--8b396753927fe6da
      build_id: bd-8b396753927fe6da_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/39/3935f8d7507f85fd20e073f0625bb6bdff8aa1b6044f4bbb720c9a8063ea0390/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/cnvkit/fix/.conda-lock/linux_amd64-bd-288e98d6210b7304_1.txt
