name: chromap_chromap
description: |
  Performs preprocessing and alignment of chromatin fastq files to fasta reference files using chromap.
keywords:
  - chromap
  - alignment
  - map
  - fastq
  - bam
  - sam
  - hi-c
  - atac-seq
  - chip-seq
  - trimming
  - duplicate removal
tools:
  - chromap:
      description: |
        Fast alignment and preprocessing of chromatin profiles
      homepage: https://github.com/haowenz/chromap
      documentation: https://github.com/haowenz/chromap
      tool_dev_url: https://github.com/haowenz/chromap
      licence: ["GPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing information for the fasta
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: Reference genome FASTA file
        pattern: "*.{fa,fasta,fna}"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
  - - meta3:
        type: map
        description: |
          Groovy Map containing information for the index
          e.g. [ id:'test' ]
    - index:
        type: file
        description: |
          Chromap genome index files (*.index)
        ontologies: []
  - barcodes:
      type: file
      description: |
        Cell barcode files
      ontologies: []
  - whitelist:
      type: file
      description: |
        Cell barcode whitelist file
      ontologies: []
  - chr_order:
      type: file
      description: |
        Custom chromosome order
      ontologies: []
  - pairs_chr_order:
      type: file
      description: |
        Natural chromosome order for pairs flipping
      ontologies: []
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bed.gz":
          type: file
          description: BED file
          pattern: "*.bed.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: BAM file
          pattern: "*.bam"
          ontologies: []
  tagAlign:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tagAlign.gz":
          type: file
          description: tagAlign file
          pattern: "*.tagAlign.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  pairs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.pairs.gz":
          type: file
          description: pairs file
          pattern: "*.pairs.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_chromap:
    - - ${task.process}:
          type: string
          description: The name of the process
      - chromap:
          type: string
          description: The name of the tool
      - chromap --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - chromap:
          type: string
          description: The name of the tool
      - chromap --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
  - "@joseespinosa"
maintainers:
  - "@mahesh-panchal"
  - "@joseespinosa"
