name: "shinyngs_staticexploratory"
description: Make exploratory plots for analysis of matrix data, including PCA, Boxplots and density plots
keywords:
  - exploratory
  - plot
  - boxplot
  - density
  - PCA
tools:
  - "shinyngs":
      description: "Provides Shiny applications for various array and NGS applications. Currently very RNA-seq centric, with plans for expansion."
      homepage: "https://github.com/pinin4fjords/shinyngs"
      documentation: "https://rawgit.com/pinin4fjords/shinyngs/master/vignettes/shinyngs.html"
      tool_dev_url: "https://github.com/pinin4fjords/shinyngs"
      licence: ["AGPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing information on variables for use in plots,
          probably experimental information, but at a minimum an id.
          e.g. [ id:'treatment' ]
    - sample:
        type: file
        description: |
          CSV-format sample sheet with sample metadata
        ontologies: []
    - feature_meta:
        type: file
        description: |
          TSV-format feature (e.g. gene) metadata
        ontologies: []
    - assay_files:
        type: file
        description: |
          List of TSV-format matrix files representing different measures for the same samples (e.g. raw and normalised).
        ontologies: []
    - variable:
        type: string
        description: |
          Variable to use for the contrast variable in the plots.
output:
  boxplots_png:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/boxplot.png":
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
  boxplots_html:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/html/boxplot.html":
          type: file
          description: |
            Meta-keyed tuple containing HTML output for box plots covering input
            matrices.
          ontologies: []
  densities_png:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/density.png":
          type: file
          description: |
            Meta-keyed tuple containing PNG output for density plots
            covering input matrices.
          ontologies: []
  densities_html:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/html/density.html":
          type: file
          description: |
            Meta-keyed tuple containing HTML output for density plots
            covering input matrices.
          ontologies: []
  pca2d_png:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/pca2d.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG output for 2D PCA plots covering
            specified input matrix (by default the last one in the input list.
          ontologies: []
  pca2d_html:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/html/pca2d.html":
          type: file
          description: |
            Meta-keyed tuple containing an HTML output for 2D PCA plots covering
            specified input matrix (by default the last one in the input list.
          ontologies: []
  pca3d_png:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/pca3d.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG output for 3D PCA plots covering
            specified input matrix (by default the last one in the input list.
          ontologies: []
  pca3d_html:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/html/pca3d.html":
          type: file
          description: |
            Meta-keyed tuple containing an HTML output for 3D PCA plots covering
            specified input matrix (by default the last one in the input list.
          ontologies: []
  mad_png:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/mad_correlation.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG output for MAD correlation plots
            covering specified input matrix (by default the last one in the input
            list.
          ontologies: []
  mad_html:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/html/mad_correlation.html":
          type: file
          description: HTML output for MAD correlation plots
          pattern: "*{.html}"
          ontologies: []
  dendro:
    - - meta:
          type: file
          description: |
            Meta-keyed tuple containing PNG output for box plots covering input
            matrices.
          ontologies: []
      - "*/png/sample_dendrogram.png":
          type: file
          description: |
            Meta-keyed tuple containing a PNG, for a sample clustering
            dendrogramcovering specified input matrix (by default the last one in
            the input list.
          ontologies: []
  versions_shinyngs:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - shinyngs:
          type: string
          description: The name of the tool
      - 'Rscript -e "library(shinyngs); cat(as.character(packageVersion(''shinyngs'')))"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/r-shinyngs:3.1.1--b5595b301bfbfd4d
      build_id: bd-b5595b301bfbfd4d_2
      scan_id: sc-73b4cbdd1930464e_1
    linux/arm64:
      name: community.wave.seqera.io/library/r-shinyngs:3.1.1--4d71a4d10942e43f
      build_id: bd-4d71a4d10942e43f_2
      scan_id: sc-72596f6b93ff3200_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.1.1--60831a2d7cd7ae94
      build_id: bd-60831a2d7cd7ae94_2
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/6f/6fff209824ab2042c6f09b68d257d59ae4e0ea7410dad923089db9c5c0dbd683/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/r-shinyngs:3.1.1--791778d7e2758322
      build_id: bd-791778d7e2758322_2
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8a/8acde9b0bc0374d51ca50f3e49fb0f26a6fb394d277b3af5e276de8bf1786610/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/shinyngs/staticexploratory/.conda-lock/linux_amd64-bd-b5595b301bfbfd4d_2.txt
    linux/arm64:
      lock_file: modules/nf-core/shinyngs/staticexploratory/.conda-lock/linux_arm64-bd-4d71a4d10942e43f_2.txt
