name: Fix linting from a comment
on:
  issue_comment:
    types: [created] # Add "@nf-core-bot fix linting" as a PR comment to trigger this workflow.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}

permissions: {}

jobs:
  fix-linting:
    if: >-
      github.event.issue.pull_request && contains(github.event.comment.body,
      '@nf-core-bot fix linting')
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    uses: nf-core/actions/.github/workflows/fix-linting.yml@v1
    secrets:
      BOT_TOKEN: ${{ secrets.nf_core_bot_auth_token }}
