name: Run when nf-test tests are skipped
on:
  push:
    branches:
      # https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging
      - "renovate/**" # branches Renovate creates
    paths:
      - "**/meta.yml"
  pull_request:
    branches: [master]
    paths:
      - "**/meta.yml"
  merge_group:
    types: [checks_requested]
    branches: [master]

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      only-meta: ${{ steps.only-meta-check.outputs.only-meta }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: changes
        with:
          filters: |
            meta:
              - '**/meta.yml'
            other:
              - '!**/meta.yml'
      - name: Check if only meta files changed
        id: only-meta-check
        run: |
          if [[ "${{ steps.changes.outputs.meta }}" == "true" && "${{ steps.changes.outputs.other }}" == "false" ]]; then
            echo "only-meta=true" >> $GITHUB_OUTPUT
          else
            echo "only-meta=false" >> $GITHUB_OUTPUT
          fi

  confirm-pass-nf-test:
    runs-on: ubuntu-latest
    needs: check-files
    if: needs.check-files.outputs.only-meta == 'true'
    steps:
      - run: 'echo "nf-test tests were skipped"'
