name: "minimac4_impute"
description: Imputation of genotypes using a reference panel
keywords:
  - impute
  - haploype
  - genomics
tools:
  - "minimac4":
      description: "Computationally efficient genotype imputation"
      homepage: "https://github.com/statgen/Minimac4"
      documentation: "https://github.com/statgen/Minimac4"
      tool_dev_url: "https://github.com/statgen/Minimac4"
      doi: "10.1038/ng.3656"
      licence:
        - "GPL v3-or-later"
      identifier: biotools:minimac4
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - target_vcf:
        type: file
        description: Target VCF/BCF file
        pattern: "*.{vcf,bcf,vcf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016"
          - edam: "http://edamontology.org/format_3020"
    - target_index:
        type: file
        description: Target VCF/BCF file index
        pattern: "*.{csi,tbi}"
        ontologies:
          - edam: "http://edamontology.org/format_3700"
    - ref_msav:
        type: file
        description: Reference compressed MSAV file obtain through `minimac4 --compress-reference`
        pattern: "*.{msav}"
        ontologies: []
    - map:
        type: file
        description: Genetic map file
        pattern: "*.map"
        ontologies:
          - edam: "http://edamontology.org/data_1278"
    - region:
        type: string
        description: Region to perform imputation
        pattern: "(chr)?\\d*:\\d*-\\d*"
  - write_sites:
      type: boolean
      description: "Write the sites-only file"
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.${extension}":
          type: file
          description: Imputed variants file
          pattern: "${prefix}.${extension}"
          ontologies:
            - edam: "http://edamontology.org/format_3016"
            - edam: "http://edamontology.org/format_3020"
  sites:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.sites.vcf.gz":
          type: file
          description: Sites-only file (output of `--sites`)
          pattern: "${prefix}.sites.vcf.gz"
          ontologies: []
  versions_minimac4:
    - - ${task.process}:
          type: string
          description: The name of the process
      - minimac4:
          type: string
          description: The name of the tool
      - minimac4 --version |& sed '1!d ; s/minimac v//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - minimac4:
          type: string
          description: The name of the tool
      - minimac4 --version |& sed '1!d ; s/minimac v//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@LouisLeNezet"
maintainers:
  - "@LouisLeNezet"
