---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::ribodetector=0.3.3"
  - "pytorch::pytorch"
  - "pytorch::pytorch-cuda=12.4"
